# Generated by Django 2.1.15 on 2020-04-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='부서',
        ),
        migrations.AddField(
            model_name='user',
            name='부서',
            field=models.ManyToManyField(null=True, related_name='user', to='users.Part'),
        ),
    ]
