# Generated by Django 2.1.15 on 2020-05-05 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200402_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nowPart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nowuser', to='users.Part'),
        ),
    ]
