# Generated by Django 2.1.15 on 2020-02-09 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StandardInformation', '0003_auto_20200209_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureCheckRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('점검일', models.DateField()),
                ('점검내용', models.CharField(max_length=100)),
                ('특이사항', models.TextField()),
                ('계측기', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StandardInformation.Measure')),
                ('점검자', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='계측기점검등록', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '계측기점검등록',
                'verbose_name_plural': '계측기점검등록',
            },
        ),
    ]
