# Generated by Django 2.1.15 on 2020-12-27 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StandardInformation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureCheckRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('점검일', models.DateField()),
                ('점검내용', models.CharField(max_length=100)),
                ('특이사항', models.TextField()),
            ],
            options={
                'verbose_name': '계측기점검등록',
                'verbose_name_plural': '계측기점검등록',
            },
        ),
        migrations.CreateModel(
            name='MeasureRepairRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('수리일', models.DateField()),
                ('수리부문', models.CharField(max_length=100)),
                ('수리내용', models.CharField(max_length=100)),
                ('file', models.ImageField(blank=True, help_text='계측기수리 사진을 첨부해주세요.', null=True, upload_to='images')),
                ('특이사항', models.TextField()),
                ('계측기', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StandardInformation.Measure')),
            ],
            options={
                'verbose_name': '계측기수리등록',
                'verbose_name_plural': '계측기수리등록',
            },
        ),
    ]
