# Generated by Django 2.1.15 on 2020-12-27 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StandardInformation', '0002_auto_20201227_1834'),
        ('measures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurerepairregister',
            name='수리자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='계측기수리등록', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='measurecheckregister',
            name='계측기',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StandardInformation.Measure'),
        ),
        migrations.AddField(
            model_name='measurecheckregister',
            name='점검자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='계측기점검등록', to=settings.AUTH_USER_MODEL),
        ),
    ]
