# Generated by Django 2.1.15 on 2020-02-09 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0002_measurerepairregister'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurerepairregister',
            old_name='수리내용사진첨부',
            new_name='file',
        ),
    ]
