# Generated by Django 2.1.15 on 2020-04-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200420_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnermigrate',
            name='Excelfile',
            field=models.FileField(null=True, upload_to='migrate'),
        ),
    ]
