# Generated by Django 2.1.15 on 2020-12-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('작성일', models.DateField(auto_now=True)),
                ('거래처구분', models.CharField(choices=[('고객', '고객'), ('대리점', '대리점'), ('공급처', '공급처')], default='공급처', max_length=4)),
                ('거래처코드', models.CharField(max_length=50, null=True)),
                ('거래처명', models.CharField(max_length=70, null=True)),
                ('사업자등록번호', models.CharField(max_length=50, null=True)),
                ('연락처', models.CharField(blank=True, max_length=50)),
                ('이메일', models.EmailField(max_length=254)),
                ('사업장주소', models.CharField(blank=True, max_length=70, null=True)),
                ('사업자등록증첨부', models.FileField(blank=True, null=True, upload_to='')),
                ('특이사항', models.TextField(blank=True, null=True)),
                ('사용여부', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '고객',
                'verbose_name_plural': '고객',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('자재코드', models.CharField(blank=True, max_length=120)),
                ('품목', models.CharField(blank=True, choices=[('자재', '자재'), ('부분품', '부분품'), ('상품', '상품')], default='자재', max_length=4, null=True)),
                ('자재품명', models.CharField(blank=True, max_length=100)),
                ('규격', models.CharField(blank=True, max_length=30)),
                ('단위', models.CharField(blank=True, choices=[('EA', 'EA'), ('ROLL', 'ROLL'), ('BOX', 'BOX'), ('SET', 'SET'), ('봉', '봉')], default='EA', max_length=4)),
                ('단가', models.IntegerField(null=True)),
                ('특이사항', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '자재',
                'verbose_name_plural': '자재',
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('계측기코드', models.CharField(blank=True, max_length=40, null=True)),
                ('계측기명', models.CharField(blank=True, max_length=40, null=True)),
                ('자산관리번호', models.CharField(max_length=40, null=True)),
                ('계측기규격', models.CharField(blank=True, max_length=40, null=True)),
                ('설치년월일', models.DateField(null=True)),
                ('사용공정명', models.CharField(blank=True, max_length=40, null=True)),
                ('설치장소', models.CharField(blank=True, max_length=40, null=True)),
                ('구매금액', models.IntegerField(blank=True, null=True)),
                ('file', models.ImageField(blank=True, help_text='계측기의 사진을 첨부해주세요.', null=True, upload_to='images')),
            ],
            options={
                'verbose_name': '계측기',
                'verbose_name_plural': '계측기',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('작성일', models.DateField(auto_now=True)),
                ('거래처구분', models.CharField(choices=[('고객', '고객'), ('대리점', '대리점'), ('공급처', '공급처')], default='공급처', max_length=4)),
                ('거래처코드', models.CharField(max_length=20, null=True)),
                ('거래처명', models.CharField(max_length=50, null=True)),
                ('사업자등록번호', models.CharField(max_length=50, null=True)),
                ('거래처담당자', models.CharField(max_length=50, null=True)),
                ('연락처', models.CharField(blank=True, max_length=50)),
                ('이메일', models.EmailField(max_length=254)),
                ('사업장주소', models.CharField(blank=True, max_length=90, null=True)),
                ('사업자등록증첨부', models.FileField(blank=True, null=True, upload_to='partnerregister')),
                ('특이사항', models.TextField(blank=True, null=True)),
                ('사용여부', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '거래처',
                'verbose_name_plural': '거래처',
            },
        ),
        migrations.CreateModel(
            name='RackProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('작성일', models.DateField(auto_now=True)),
                ('랙시리얼코드', models.CharField(blank=True, max_length=40)),
                ('현장명', models.CharField(blank=True, max_length=60)),
                ('규격', models.CharField(blank=True, max_length=30)),
                ('단위', models.CharField(blank=True, max_length=30)),
                ('단가', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '랙제품',
                'verbose_name_plural': '랙제품',
            },
        ),
        migrations.CreateModel(
            name='RackProductMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('랙구성', models.CharField(blank=True, choices=[('단품', '단품'), ('자재', '자재')], default='단품', max_length=4)),
                ('수량', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': '랙구성단품및자재',
                'verbose_name_plural': '랙구성단품및자재',
            },
        ),
        migrations.CreateModel(
            name='SingleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('작성일', models.DateField(auto_now=True)),
                ('모델코드', models.CharField(max_length=80)),
                ('모델명', models.CharField(max_length=30)),
                ('규격', models.CharField(blank=True, max_length=80, null=True)),
                ('단위', models.CharField(blank=True, max_length=10, null=True)),
                ('단가', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '단품제품',
                'verbose_name_plural': '단품제품',
            },
        ),
        migrations.CreateModel(
            name='SingleProductMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('수량', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '단품제품구성자재',
                'verbose_name_plural': '단품제품구성자재',
            },
        ),
        migrations.CreateModel(
            name='SupplyPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('작성일', models.DateField(auto_now=True)),
                ('거래처구분', models.CharField(choices=[('고객', '고객'), ('대리점', '대리점'), ('공급처', '공급처')], default='공급처', max_length=4)),
                ('거래처코드', models.CharField(max_length=50, null=True)),
                ('거래처명', models.CharField(max_length=70, null=True)),
                ('사업자등록번호', models.CharField(max_length=50, null=True)),
                ('연락처', models.CharField(blank=True, max_length=50)),
                ('이메일', models.EmailField(blank=True, max_length=254)),
                ('사업장주소', models.CharField(blank=True, max_length=70, null=True)),
                ('사업자등록증첨부', models.FileField(blank=True, upload_to='')),
                ('특이사항', models.TextField(blank=True)),
                ('사용여부', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '공급처',
                'verbose_name_plural': '공급처',
            },
        ),
    ]
