# Generated by Django 2.1.15 on 2020-02-06 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('자재코드', models.CharField(blank=True, max_length=160)),
                ('자재품명', models.CharField(blank=True, max_length=160)),
                ('규격', models.CharField(blank=True, max_length=160)),
                ('단위', models.CharField(blank=True, choices=[('EA', 'EA'), ('ROLL', 'ROLL'), ('BOX', 'BOX'), ('SET', 'SET'), ('봉', '봉')], default='EA', max_length=4)),
                ('단가', models.IntegerField(null=True)),
                ('특이사항', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '자재',
                'verbose_name_plural': '자재',
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('계측기코드', models.CharField(blank=True, max_length=160)),
                ('계측기명', models.CharField(blank=True, max_length=160)),
                ('자산관리번호', models.IntegerField()),
                ('계측기규격', models.CharField(blank=True, max_length=160)),
                ('설치년월일', models.DateField()),
                ('사용공정명', models.CharField(blank=True, max_length=160)),
                ('설치장소', models.CharField(blank=True, max_length=160)),
                ('file', models.ImageField(blank=True, help_text='계측기의 사진을 첨부해주세요.', upload_to='images')),
            ],
            options={
                'verbose_name': '계측기',
                'verbose_name_plural': '계측기',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('작성일', models.DateField(auto_now=True)),
                ('거래처구분', models.CharField(blank=True, choices=[('고객', '고객'), ('대리점', '대리점'), ('공급처', '공급처')], default='공급처', max_length=4)),
                ('거래처코드', models.IntegerField(null=True)),
                ('거래처명', models.CharField(blank=True, max_length=160)),
                ('사업자등록번호', models.IntegerField(null=True)),
                ('연락처', models.IntegerField()),
                ('이메일', models.EmailField(max_length=254)),
                ('사업장주소', models.CharField(blank=True, max_length=160)),
                ('사업자등록증첨부', models.FileField(blank=True, upload_to='')),
                ('특이사항', models.TextField(blank=True)),
                ('사용여부', models.BooleanField(default=False)),
                ('담당자', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='거래처담당자', to=settings.AUTH_USER_MODEL)),
                ('작성자', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='거래처작성자', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '거래처',
                'verbose_name_plural': '거래처',
            },
        ),
        migrations.CreateModel(
            name='RackProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('작성일', models.DateField(auto_now=True)),
                ('랙시리얼코드', models.CharField(blank=True, max_length=160)),
                ('랙모델명', models.CharField(blank=True, max_length=160)),
                ('규격', models.CharField(blank=True, max_length=160)),
                ('단위', models.CharField(blank=True, max_length=160)),
                ('단가', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': '랙제품',
                'verbose_name_plural': '랙제품',
            },
        ),
        migrations.CreateModel(
            name='RackProductMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('수량', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': '랙구성단품',
                'verbose_name_plural': '랙구성단품',
            },
        ),
        migrations.CreateModel(
            name='SingleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('작성일', models.DateField(auto_now=True)),
                ('모델코드', models.CharField(blank=True, max_length=160)),
                ('모델명', models.CharField(blank=True, max_length=160)),
                ('규격', models.CharField(blank=True, max_length=160)),
                ('단위', models.CharField(blank=True, max_length=160)),
                ('단가', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': '단품제품',
                'verbose_name_plural': '단품제품',
            },
        ),
        migrations.CreateModel(
            name='SingleProductMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('수량', models.IntegerField(null=True)),
                ('단품구성자재', models.ManyToManyField(blank=True, related_name='단품구성자재', to='StandardInformation.Material')),
            ],
            options={
                'verbose_name': '단품제품구성자재',
                'verbose_name_plural': '단품제품구성자재',
            },
        ),
        migrations.CreateModel(
            name='SupplyPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('작성일', models.DateField(auto_now=True)),
                ('거래처구분', models.CharField(blank=True, choices=[('고객', '고객'), ('대리점', '대리점'), ('공급처', '공급처')], default='공급처', max_length=4)),
                ('거래처코드', models.IntegerField(null=True)),
                ('거래처명', models.CharField(blank=True, max_length=160)),
                ('사업자등록번호', models.IntegerField(null=True)),
                ('연락처', models.IntegerField()),
                ('이메일', models.EmailField(max_length=254)),
                ('사업장주소', models.CharField(blank=True, max_length=160)),
                ('사업자등록증첨부', models.FileField(blank=True, upload_to='')),
                ('특이사항', models.TextField(blank=True)),
                ('사용여부', models.BooleanField(default=False)),
                ('공급처담당자', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='공급처거래처담당자', to=settings.AUTH_USER_MODEL)),
                ('공급처작성자', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='공급처거래처작성자', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '공급처',
                'verbose_name_plural': '공급처',
            },
        ),
        migrations.AddField(
            model_name='singleproduct',
            name='단품구성자재',
            field=models.ManyToManyField(blank=True, related_name='단품제품', to='StandardInformation.SingleProductMaterial'),
        ),
        migrations.AddField(
            model_name='singleproduct',
            name='작성자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='단품제품작성자', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rackproductmaterial',
            name='랙구성단품',
            field=models.ManyToManyField(blank=True, related_name='랙구성단품', to='StandardInformation.SingleProduct'),
        ),
        migrations.AddField(
            model_name='rackproduct',
            name='랙구성단품',
            field=models.ManyToManyField(blank=True, related_name='랙제품', to='StandardInformation.RackProductMaterial'),
        ),
        migrations.AddField(
            model_name='rackproduct',
            name='작성자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='랙제품작성자', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='material',
            name='자재공급업체',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='자재공급업체', to='StandardInformation.SupplyPartner'),
        ),
    ]
