# Generated by Django 2.1.15 on 2020-12-27 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StandardInformation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplypartner',
            name='공급처담당자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='공급처거래처담당자', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplypartner',
            name='공급처작성자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='공급처거래처작성자', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='singleproductmaterial',
            name='단품구성자재',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='단품구성자재', to='StandardInformation.Material'),
        ),
        migrations.AddField(
            model_name='singleproductmaterial',
            name='단품모델',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='단품구성자재', to='StandardInformation.SingleProduct'),
        ),
        migrations.AddField(
            model_name='singleproduct',
            name='작성자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='단품제품작성자', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rackproductmaterial',
            name='랙구성단품',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='랙구성단품', to='StandardInformation.SingleProduct'),
        ),
        migrations.AddField(
            model_name='rackproductmaterial',
            name='랙구성자재',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='랙구성자재', to='StandardInformation.Material'),
        ),
        migrations.AddField(
            model_name='rackproductmaterial',
            name='랙모델',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='랙구성단품', to='StandardInformation.RackProduct'),
        ),
        migrations.AddField(
            model_name='rackproduct',
            name='작성자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='랙제품작성자', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partner',
            name='담당자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='거래처담당자', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partner',
            name='작성자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='거래처작성자', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='measure',
            name='작성자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='계측기작성자', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='material',
            name='자재공급업체',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='제공자재', to='StandardInformation.SupplyPartner'),
        ),
        migrations.AddField(
            model_name='material',
            name='작성자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='자재제품작성자', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerpartner',
            name='고객담당자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='고객거래처담당자', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerpartner',
            name='고객작성자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='고객거래처작성자', to=settings.AUTH_USER_MODEL),
        ),
    ]
