# Generated by Django 2.1.15 on 2020-02-09 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StandardInformation', '0002_auto_20200209_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleproductmaterial',
            name='단품구성자재',
            field=models.ManyToManyField(related_name='단품구성자재', to='StandardInformation.Material'),
        ),
        migrations.AlterField(
            model_name='singleproductmaterial',
            name='단품모델',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='단품구성자재', to='StandardInformation.SingleProduct'),
        ),
        migrations.AlterField(
            model_name='singleproductmaterial',
            name='수량',
            field=models.IntegerField(default=0),
        ),
    ]
