# Generated by Django 2.1.15 on 2020-12-27 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StandardInformation', '0002_auto_20201227_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rackproductmaterial',
            name='랙모델',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='랙구성단품', to='StandardInformation.RackProduct'),
        ),
    ]
