# Generated by Django 2.1.15 on 2020-02-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StandardInformation', '0003_auto_20200209_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='사업자등록증첨부',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='partner',
            name='사업장주소',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
