# Generated by Django 2.1.15 on 2020-12-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StandardInformation', '0003_auto_20201227_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='규격',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='material',
            name='품목',
            field=models.CharField(blank=True, choices=[('자재', '자재'), ('부분품', '부분품'), ('상품', '상품')], default='자재', max_length=10, null=True),
        ),
    ]
