# Generated by Django 2.1.15 on 2020-12-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StandardInformation', '0004_auto_20201227_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='품목',
            field=models.CharField(blank=True, choices=[('자재', '자재'), ('부분품', '부분품'), ('상품', '상품')], default='자재', max_length=30, null=True),
        ),
    ]
