# Generated by Django 2.1.15 on 2020-02-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StandardInformation', '0004_auto_20200209_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='거래처코드',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
