# Generated by Django 2.1.15 on 2020-02-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StandardInformation', '0005_auto_20200212_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpartner',
            name='거래처구분',
            field=models.CharField(choices=[('고객', '고객'), ('대리점', '대리점'), ('공급처', '공급처')], default='공급처', max_length=4),
        ),
        migrations.AlterField(
            model_name='customerpartner',
            name='거래처명',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='customerpartner',
            name='거래처코드',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerpartner',
            name='사업자등록번호',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerpartner',
            name='사업자등록증첨부',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customerpartner',
            name='사업장주소',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='customerpartner',
            name='연락처',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customerpartner',
            name='특이사항',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='거래처구분',
            field=models.CharField(choices=[('고객', '고객'), ('대리점', '대리점'), ('공급처', '공급처')], default='공급처', max_length=4),
        ),
        migrations.AlterField(
            model_name='partner',
            name='거래처명',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='사업자등록번호',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='연락처',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='partner',
            name='특이사항',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplypartner',
            name='거래처구분',
            field=models.CharField(choices=[('고객', '고객'), ('대리점', '대리점'), ('공급처', '공급처')], default='공급처', max_length=4),
        ),
        migrations.AlterField(
            model_name='supplypartner',
            name='거래처명',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='supplypartner',
            name='거래처코드',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplypartner',
            name='사업자등록번호',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplypartner',
            name='연락처',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='supplypartner',
            name='이메일',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
