# Generated by Django 2.1.15 on 2020-12-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StandardInformation', '0005_auto_20201227_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='단위',
            field=models.CharField(blank=True, choices=[('EA', 'EA'), ('ROLL', 'ROLL'), ('BOX', 'BOX'), ('SET', 'SET'), ('봉', '봉')], default='EA', max_length=40),
        ),
    ]
