# Generated by Django 2.1.15 on 2020-02-13 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StandardInformation', '0007_auto_20200213_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='사업자등록증첨부',
            field=models.FileField(blank=True, null=True, upload_to='partnerregister'),
        ),
        migrations.RemoveField(
            model_name='singleproductmaterial',
            name='단품구성자재',
        ),
        migrations.AddField(
            model_name='singleproductmaterial',
            name='단품구성자재',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='단품구성자재', to='StandardInformation.Material'),
        ),
    ]
