# Generated by Django 2.1.15 on 2020-02-15 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StandardInformation', '0008_auto_20200213_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rackproductmaterial',
            name='랙구성단품',
        ),
        migrations.AddField(
            model_name='rackproductmaterial',
            name='랙구성단품',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='랙구성단품', to='StandardInformation.SingleProduct'),
        ),
        migrations.RemoveField(
            model_name='rackproductmaterial',
            name='랙구성자재',
        ),
        migrations.AddField(
            model_name='rackproductmaterial',
            name='랙구성자재',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='랙구성자재', to='StandardInformation.Material'),
        ),
    ]
