# Generated by Django 2.1.15 on 2020-03-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StandardInformation', '0009_auto_20200215_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='거래처담당자',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
