# Generated by Django 2.1.15 on 2020-03-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StandardInformation', '0010_partner_거래처담당자'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='자산관리번호',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
