# Generated by Django 2.1.15 on 2020-03-16 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StandardInformation', '0013_material_작성자'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='작성자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='자재제품작성자', to=settings.AUTH_USER_MODEL),
        ),
    ]
