# Generated by Django 2.1.15 on 2020-04-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StandardInformation', '0014_auto_20200316_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='구매금액',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='계측기규격',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='계측기명',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='계측기코드',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='사용공정명',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='설치년월일',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='설치장소',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
