# Generated by Django 2.1.15 on 2020-04-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StandardInformation', '0015_auto_20200414_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='특이사항',
            field=models.TextField(blank=True, null=True),
        ),
    ]
