# Generated by Django 2.1.15 on 2020-08-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StandardInformation', '0016_auto_20200420_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleproduct',
            name='모델명',
            field=models.CharField(max_length=30),
        ),
    ]
