# Generated by Django 2.1.15 on 2020-11-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StandardInformation', '0017_auto_20200826_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='자재코드',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='material',
            name='자재품명',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
