# Generated by Django 2.1.15 on 2020-12-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StandardInformation', '0018_auto_20201113_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleproduct',
            name='규격',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='singleproduct',
            name='단가',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='singleproduct',
            name='단위',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='singleproduct',
            name='모델코드',
            field=models.CharField(max_length=80),
        ),
    ]
