# Generated by Django 2.1.15 on 2020-02-09 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StandardInformation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOfRackProductOutRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('출하요청수량', models.IntegerField()),
                ('출하요청일', models.DateField()),
                ('랙', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='랙출하요청', to='StandardInformation.RackProduct')),
                ('출하요청자', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='랙출하요청', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '랙출하요청',
                'verbose_name_plural': '랙출하요청',
            },
        ),
    ]
