# Generated by Django 2.1.15 on 2020-02-09 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockrock', '0002_auto_20200209_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOfRackProductOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('출하일', models.DateField(null=True)),
                ('출하수량', models.IntegerField(null=True)),
                ('거래명세서첨부', models.FileField(blank=True, help_text='거래명세서를 첨부해주세요.', null=True, upload_to='deal')),
                ('랙출하요청', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='랙출하등록', to='stockrock.StockOfRackProductOutRequest')),
                ('출하자', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='랙출하등록', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '랙출하등록',
                'verbose_name_plural': '랙출하등록',
            },
        ),
    ]
