# Generated by Django 2.1.15 on 2020-02-09 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StandardInformation', '0001_initial'),
        ('producemanages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '최종검사',
                'verbose_name_plural': '최종검사',
            },
        ),
        migrations.CreateModel(
            name='FinalCheckRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('검시일', models.DateField()),
                ('CR', models.CharField(blank=True, max_length=20, null=True)),
                ('MA', models.CharField(blank=True, max_length=20, null=True)),
                ('MI', models.CharField(blank=True, max_length=20, null=True)),
                ('검사수준', models.CharField(blank=True, max_length=40, null=True)),
                ('Sample방식', models.CharField(blank=True, max_length=20, null=True)),
                ('결점수', models.CharField(blank=True, max_length=20, null=True)),
                ('전원전압', models.CharField(blank=True, max_length=20, null=True)),
                ('POWERTRANS', models.CharField(blank=True, max_length=20, null=True)),
                ('FUSE_전_ULUSA', models.CharField(blank=True, max_length=20, null=True)),
                ('LABEL_인쇄물', models.CharField(blank=True, max_length=50, null=True)),
                ('기타출하위치', models.CharField(blank=True, max_length=50, null=True)),
                ('내용물', models.CharField(blank=True, max_length=50, null=True)),
                ('포장검사', models.CharField(blank=True, choices=[('OK', 'OK'), ('NO', 'NO')], default='OK', max_length=10)),
                ('동작검사', models.CharField(blank=True, choices=[('OK', 'OK'), ('NO', 'NO')], default='OK', max_length=10)),
                ('내부검사', models.CharField(blank=True, choices=[('OK', 'OK'), ('NO', 'NO')], default='OK', max_length=10)),
                ('외관검사', models.CharField(blank=True, choices=[('OK', 'OK'), ('NO', 'NO')], default='OK', max_length=10)),
                ('내압검사', models.CharField(blank=True, choices=[('OK', 'OK'), ('NO', 'NO')], default='OK', max_length=10)),
                ('내용물확인', models.CharField(blank=True, choices=[('OK', 'OK'), ('NO', 'NO')], default='OK', max_length=10)),
                ('가_감전압', models.CharField(max_length=50)),
                ('HI_POT_내부검사', models.CharField(max_length=50)),
                ('REMARK', models.TextField(max_length=80)),
                ('부적합수량', models.IntegerField()),
                ('적합수량', models.IntegerField()),
                ('검시자', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='최종검사등록', to=settings.AUTH_USER_MODEL)),
                ('최종검사의뢰', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='최종검사등록', to='qualitycontrols.FinalCheck')),
            ],
            options={
                'verbose_name': '최종검사결과등록',
                'verbose_name_plural': '최종검사결과등록',
            },
        ),
        migrations.CreateModel(
            name='LowMetarial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('자재부적합보고서번호', models.CharField(max_length=20)),
                ('검토일', models.DateField()),
                ('부적합자재의내용과검토방안', models.TextField(blank=True, max_length=150, null=True)),
                ('처리방안', models.CharField(blank=True, choices=[('재작업', '재작업'), ('수리', '수리'), ('특채(수리후)', '특채(수리후)'), ('특채(무수리)', '특채(무수리)'), ('반품', '반품'), ('폐기', '폐기'), ('기타', '기타')], default='기타', max_length=10, null=True)),
                ('검토자', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='자재부적합보고서', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '자재부적합보고서',
                'verbose_name_plural': '자재부적합보고서',
            },
        ),
        migrations.CreateModel(
            name='MaterialCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('수입검사코드', models.CharField(max_length=20)),
                ('검사지침서번호', models.CharField(max_length=20)),
                ('검사일자', models.DateField()),
                ('검사항목', models.CharField(blank=True, max_length=20, null=True)),
                ('판정기준', models.CharField(blank=True, max_length=20, null=True)),
                ('시료크기', models.IntegerField()),
                ('합격수량', models.IntegerField()),
                ('불합격수량', models.IntegerField()),
                ('불합격내용', models.TextField(blank=True, max_length=100, null=True)),
                ('검사자', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='수입검사', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '수입검사',
                'verbose_name_plural': '수입검사',
            },
        ),
        migrations.CreateModel(
            name='MaterialCheckRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('수입검사의뢰코드', models.CharField(max_length=30)),
                ('수량', models.IntegerField()),
                ('의뢰자', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='수입검사의뢰', to=settings.AUTH_USER_MODEL)),
                ('자재', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='수입검사의뢰', to='StandardInformation.Material')),
            ],
            options={
                'verbose_name': '수입검사의뢰',
                'verbose_name_plural': '수입검사의뢰',
            },
        ),
        migrations.CreateModel(
            name='RepairRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('불량위치및자재', models.TextField(max_length=300)),
                ('특이사항', models.TextField(blank=True, max_length=300, null=True)),
                ('수리내용', models.TextField(blank=True, max_length=300, null=True)),
                ('실수리수량', models.IntegerField()),
                ('폐기수량', models.IntegerField()),
                ('최종검사결과', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='부적합등록', to='qualitycontrols.FinalCheckRegister')),
            ],
            options={
                'verbose_name': '수리내역서',
                'verbose_name_plural': '수리내역서',
            },
        ),
        migrations.AddField(
            model_name='materialcheck',
            name='수입검사의뢰',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualitycontrols.MaterialCheckRegister'),
        ),
        migrations.AddField(
            model_name='lowmetarial',
            name='수입검사',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qualitycontrols.MaterialCheck'),
        ),
        migrations.AddField(
            model_name='finalcheck',
            name='수리내역서',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='최종검사', to='qualitycontrols.RepairRegister'),
        ),
        migrations.AddField(
            model_name='finalcheck',
            name='작업지시서',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='최종검사', to='producemanages.WorkOrderRegister'),
        ),
    ]
