# Generated by Django 2.1.15 on 2020-12-27 18:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afterservices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '최종검사',
                'verbose_name_plural': '최종검사',
            },
        ),
        migrations.CreateModel(
            name='FinalCheckRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('최종검사코드', models.CharField(blank=True, max_length=20, null=True)),
                ('검시일', models.DateField(blank=True, null=True)),
                ('치명적불량', models.CharField(max_length=20, null=True)),
                ('중불량', models.CharField(max_length=20, null=True)),
                ('경불량', models.CharField(max_length=20, null=True)),
                ('검사수준', models.CharField(max_length=40, null=True)),
                ('샘플링방식', models.CharField(max_length=20, null=True)),
                ('결점수', models.CharField(max_length=20, null=True)),
                ('전원전압', models.CharField(choices=[('DC 24V', 'DC 24V'), ('AC 220V', 'AC 220V')], default='DC 24V', max_length=20, null=True)),
                ('POWERTRANS', models.CharField(choices=[('T-EPD2083-01', 'T-EPD2083-01'), ('T-EPB2032-01', 'T-EPB2032-01'), ('T-EPA2403-01', 'T-EPA2403-01'), ('T-EPA2243-01', 'T-EPA2243-01'), ('T-EPA2123-01', 'T-EPA2123-01'), ('T-EWA2240-01', 'T-EWA2240-01'), ('EWA2120-01', 'EWA2120-01'), ('R-EWA2360-01', 'R-EWA2360-01')], default='T-EPD2083-01', max_length=20, null=True)),
                ('FUSE_전_ULUSA', models.CharField(choices=[('31.8mm 1A', '31.8mm 1A'), ('31.8mm 2A', '31.8mm 2A'), ('31.8mm 3A', '31.8mm 3A'), ('31.8mm 4A', '31.8mm 4A'), ('31.8mm 5A', '31.8mm 5A'), ('31.8mm 10A', '31.8mm 10A'), ('31.8mm 15A', '31.8mm 15A'), ('20mm 2A', '20mm 2A'), ('20mm 3.15A', '20mm 3.15A'), ('20mm 5A', '20mm 5A')], default='31.8mm 1A', max_length=20, null=True)),
                ('LABEL_인쇄물', models.CharField(choices=[('후면 좌측', '후면 좌측'), ('후면 우측', '후면 우측'), ('후면 중심', '후면 중심'), ('후면 우측아래', '후면 우측아래'), ('후면 좌측아래', '후면 좌측아래')], default='후면 좌측', max_length=20, null=True)),
                ('기타출하위치', models.CharField(blank=True, max_length=50, null=True)),
                ('내용물', models.CharField(choices=[('있음', '있음'), ('없음', '없음')], default='있음', max_length=20, null=True)),
                ('포장검사', models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], default='OK', max_length=20, null=True)),
                ('동작검사', models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], default='OK', max_length=20, null=True)),
                ('내부검사', models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], default='OK', max_length=20, null=True)),
                ('외관검사', models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], default='OK', max_length=20, null=True)),
                ('내압검사_DC', models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], default='OK', max_length=20, null=True)),
                ('내압검사_AC', models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], default='OK', max_length=20, null=True)),
                ('내용물확인', models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], default='OK', max_length=20, null=True)),
                ('가_감전압', models.CharField(blank=True, max_length=50, null=True)),
                ('HI_POT_내부검사', models.CharField(blank=True, max_length=50, null=True)),
                ('특이사항', models.TextField(blank=True, max_length=80, null=True)),
                ('부적합수량', models.IntegerField(null=True)),
                ('적합수량', models.IntegerField(null=True)),
                ('동작이상유무', models.CharField(blank=True, max_length=100, null=True)),
                ('외형이상유무', models.CharField(blank=True, max_length=100, null=True)),
                ('수리내역', models.CharField(blank=True, max_length=100, null=True)),
                ('특기사항', models.CharField(blank=True, max_length=100, null=True)),
                ('수리비', models.CharField(blank=True, choices=[('무상', '무상'), ('유상', '유상')], max_length=100, null=True)),
                ('기본요금', models.IntegerField(blank=True, null=True)),
                ('부품비', models.IntegerField(blank=True, null=True)),
                ('택배', models.CharField(blank=True, choices=[('선불', '선불'), ('신용', '신용'), ('착불', '착불')], max_length=100, null=True)),
                ('화물', models.CharField(blank=True, max_length=100, null=True)),
                ('발송날짜', models.DateField(blank=True, null=True)),
                ('입금확인', models.DateField(blank=True, null=True)),
                ('비고', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': '최종검사결과등록',
                'verbose_name_plural': '최종검사결과등록',
            },
        ),
        migrations.CreateModel(
            name='LowMetarial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('자재부적합코드', models.CharField(max_length=20)),
                ('검토일', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('부적합자재의내용과검토방안', models.TextField(blank=True, max_length=150, null=True)),
                ('처리방안', models.CharField(choices=[('재작업', '재작업'), ('수리', '수리'), ('특채(수리후)', '특채(수리후)'), ('특채(무수리)', '특채(무수리)'), ('반품', '반품'), ('폐기', '폐기'), ('기타', '기타')], default='기타', max_length=10, null=True)),
                ('첨부파일', models.FileField(blank=True, null=True, upload_to='lowmaterial')),
            ],
            options={
                'verbose_name': '자재부적합보고서',
                'verbose_name_plural': '자재부적합보고서',
            },
        ),
        migrations.CreateModel(
            name='MaterialCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('수입검사코드', models.CharField(max_length=20)),
                ('검사지침서', models.CharField(blank=True, max_length=100, null=True)),
                ('검사일자', models.DateField(blank=True, null=True)),
                ('검사항목', models.CharField(blank=True, max_length=20, null=True)),
                ('판정기준', models.CharField(blank=True, default='AC=0, RE=1', max_length=20, null=True)),
                ('시료크기', models.IntegerField()),
                ('적합수량', models.IntegerField()),
                ('부적합수량', models.IntegerField()),
                ('부적합내용', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': '수입검사',
                'verbose_name_plural': '수입검사',
            },
        ),
        migrations.CreateModel(
            name='MaterialCheckRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('수입검사의뢰코드', models.CharField(max_length=30)),
                ('수량', models.IntegerField()),
            ],
            options={
                'verbose_name': '수입검사의뢰',
                'verbose_name_plural': '수입검사의뢰',
            },
        ),
        migrations.CreateModel(
            name='RepairRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('수리최종', models.CharField(blank=True, choices=[('최종검사결과', '최종검사결과'), ('AS', 'AS')], default=models.ManyToManyField(related_name='수리내역서', to='qualitycontrols.FinalCheckRegister'), max_length=10, null=True)),
                ('불량위치및자재', models.TextField(max_length=300, null=True)),
                ('특이사항', models.TextField(blank=True, max_length=300, null=True)),
                ('수리내용', models.TextField(blank=True, max_length=300, null=True)),
                ('실수리수량', models.IntegerField(null=True)),
                ('폐기수량', models.IntegerField(null=True)),
                ('AS수리의뢰', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='수리내역서', to='afterservices.ASRepairRequest')),
            ],
            options={
                'verbose_name': '수리내역서',
                'verbose_name_plural': '수리내역서',
            },
        ),
    ]
