# Generated by Django 2.1.15 on 2020-02-07 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producemanages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('수리내역서', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='최종검사', to='producemanages.RepairRegister')),
                ('작업지시서', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='최종검사', to='producemanages.WorkOrderRegister')),
            ],
            options={
                'verbose_name': '최종검사',
                'verbose_name_plural': '최종검사',
            },
        ),
        migrations.CreateModel(
            name='FinalCheckRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('검시일', models.DateField()),
                ('CR', models.CharField(max_length=20)),
                ('MA', models.CharField(max_length=20)),
                ('MI', models.CharField(max_length=20)),
                ('검사수준', models.CharField(max_length=40)),
                ('Sample방식', models.CharField(max_length=20)),
                ('결점수', models.CharField(max_length=20)),
                ('전원전압', models.CharField(max_length=20)),
                ('POWERTRANS', models.CharField(max_length=20)),
                ('FUSE_전_ULUSA', models.CharField(max_length=20)),
                ('LABEL_인쇄물', models.CharField(max_length=50)),
                ('기타출하위치', models.CharField(max_length=50)),
                ('내용물', models.CharField(max_length=50)),
                ('포장검사', models.CharField(blank=True, choices=[('OK', 'OK'), ('NO', 'NO')], default='OK', max_length=10)),
                ('동작검사', models.CharField(blank=True, choices=[('OK', 'OK'), ('NO', 'NO')], default='OK', max_length=10)),
                ('내부검사', models.CharField(blank=True, choices=[('OK', 'OK'), ('NO', 'NO')], default='OK', max_length=10)),
                ('외관검사', models.CharField(blank=True, choices=[('OK', 'OK'), ('NO', 'NO')], default='OK', max_length=10)),
                ('내압검사', models.CharField(blank=True, choices=[('OK', 'OK'), ('NO', 'NO')], default='OK', max_length=10)),
                ('내용물확인', models.CharField(blank=True, choices=[('OK', 'OK'), ('NO', 'NO')], default='OK', max_length=10)),
                ('가_감전압', models.CharField(max_length=50)),
                ('HI_POT_내부검사', models.CharField(max_length=50)),
                ('REMARK', models.TextField(max_length=80)),
                ('부적합수량', models.IntegerField()),
                ('적합수량', models.IntegerField()),
                ('검시자', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='최종검사등록', to=settings.AUTH_USER_MODEL)),
                ('최종검사의뢰', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='최종검사등록', to='qualitycontrols.FinalCheck')),
            ],
            options={
                'verbose_name': '최종검사결과등록',
                'verbose_name_plural': '최종검사결과등록',
            },
        ),
    ]
