# Generated by Django 2.1.15 on 2020-12-27 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StandardInformation', '0002_auto_20201227_1834'),
        ('qualitycontrols', '0001_initial'),
        ('producemanages', '0002_auto_20201227_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='repairregister',
            name='작성자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='수리내역서', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repairregister',
            name='제품',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='수리내역서', to='StandardInformation.SingleProduct'),
        ),
        migrations.AddField(
            model_name='repairregister',
            name='최종검사결과',
            field=models.ManyToManyField(related_name='수리내역서', to='qualitycontrols.FinalCheckRegister'),
        ),
        migrations.AddField(
            model_name='materialcheckregister',
            name='의뢰자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='수입검사의뢰', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialcheckregister',
            name='자재',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='수입검사의뢰', to='StandardInformation.Material'),
        ),
        migrations.AddField(
            model_name='materialcheck',
            name='검사자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='수입검사', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialcheck',
            name='수입검사의뢰',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='수입검사', to='qualitycontrols.MaterialCheckRegister'),
        ),
        migrations.AddField(
            model_name='materialcheck',
            name='자재',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='수입검사', to='StandardInformation.Material'),
        ),
        migrations.AddField(
            model_name='lowmetarial',
            name='검토자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='자재부적합보고서', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lowmetarial',
            name='수입검사',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='자재부적합보고서', to='qualitycontrols.MaterialCheck'),
        ),
        migrations.AddField(
            model_name='lowmetarial',
            name='자재',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='자재부적합보고서', to='StandardInformation.Material'),
        ),
        migrations.AddField(
            model_name='finalcheckregister',
            name='검시자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='최종검사등록', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finalcheckregister',
            name='발송자',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS총괄장발송', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finalcheckregister',
            name='수리자',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS총괄장수리', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finalcheckregister',
            name='제품',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='최종검사등록', to='StandardInformation.SingleProduct'),
        ),
        migrations.AddField(
            model_name='finalcheckregister',
            name='최종검사의뢰',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='최종검사등록', to='qualitycontrols.FinalCheck'),
        ),
        migrations.AddField(
            model_name='finalcheck',
            name='수리내역서',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='최종검사', to='qualitycontrols.RepairRegister'),
        ),
        migrations.AddField(
            model_name='finalcheck',
            name='작업지시서',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='최종검사', to='producemanages.WorkOrderRegister'),
        ),
        migrations.AddField(
            model_name='finalcheck',
            name='제품',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='최종검사', to='StandardInformation.SingleProduct'),
        ),
    ]
