# Generated by Django 2.1.15 on 2020-02-07 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qualitycontrols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepairRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('불량위치및자재', models.TextField(max_length=300)),
                ('특이사항', models.TextField(max_length=300)),
                ('수리내용', models.TextField(max_length=300)),
                ('실수리수량', models.IntegerField()),
                ('폐기수량', models.IntegerField()),
                ('최종검사결과', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='부적합등록', to='qualitycontrols.FinalCheckRegister')),
            ],
            options={
                'verbose_name': '수리내역서',
                'verbose_name_plural': '수리내역서',
            },
        ),
        migrations.AlterField(
            model_name='finalcheck',
            name='수리내역서',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='최종검사', to='qualitycontrols.RepairRegister'),
        ),
    ]
