# Generated by Django 2.1.15 on 2020-02-10 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0001_initial'),
        ('qualitycontrols', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repairregister',
            name='AS수리의뢰',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='수리내역서', to='afterservices.ASVisitContents'),
        ),
        migrations.AlterField(
            model_name='repairregister',
            name='최종검사결과',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='부적합등록', to='qualitycontrols.FinalCheckRegister'),
        ),
    ]
