# Generated by Django 2.1.15 on 2020-02-08 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StandardInformation', '0002_material_품목'),
        ('qualitycontrols', '0003_metarialincheckregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCheckRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('수입검사의뢰코드', models.CharField(max_length=30)),
                ('수량', models.IntegerField()),
                ('의뢰자', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='수입검사의뢰', to=settings.AUTH_USER_MODEL)),
                ('자재', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='수입검사의뢰', to='StandardInformation.Material')),
            ],
            options={
                'verbose_name': '수입검사의뢰',
                'verbose_name_plural': '수입검사의뢰',
            },
        ),
        migrations.DeleteModel(
            name='MetarialInCheckRegister',
        ),
    ]
