# Generated by Django 2.1.15 on 2020-02-10 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qualitycontrols', '0003_repairregister_수리최종'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalcheck',
            name='작업지시서',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='최종검사', to='producemanages.WorkOrderRegister'),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='최종검사의뢰',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='최종검사등록', to='qualitycontrols.FinalCheck'),
        ),
        migrations.AlterField(
            model_name='repairregister',
            name='AS수리의뢰',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='수리내역서', to='afterservices.ASVisitContents'),
        ),
        migrations.AlterField(
            model_name='repairregister',
            name='수리최종',
            field=models.CharField(blank=True, choices=[('최종검사결과', '최종검사결과'), ('AS', 'AS')], default=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='수리내역서', to='qualitycontrols.FinalCheckRegister'), max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='repairregister',
            name='최종검사결과',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='수리내역서', to='qualitycontrols.FinalCheckRegister'),
        ),
    ]
