# Generated by Django 2.1.15 on 2020-02-24 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qualitycontrols', '0004_auto_20200210_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='repairregister',
            name='작성자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='수리내역서', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='finalcheck',
            name='수리내역서',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='최종검사', to='qualitycontrols.RepairRegister'),
        ),
    ]
