# Generated by Django 2.1.15 on 2020-02-08 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qualitycontrols', '0004_auto_20200208_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowMetarial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('자재부적합보고서번호', models.CharField(max_length=20)),
                ('검토일', models.DateField()),
                ('부적합자재의내용과검토방안', models.TextField(max_length=150)),
                ('처리방안', models.CharField(choices=[('재작업', '재작업'), ('수리', '수리'), ('특채(수리후)', '특채(수리후)'), ('특채(무수리)', '특채(무수리)'), ('반품', '반품'), ('폐기', '폐기'), ('기타', '기타')], default='기타', max_length=10)),
                ('검토자', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='자재부적합보고서', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '자재부적합보고서',
                'verbose_name_plural': '자재부적합보고서',
            },
        ),
        migrations.CreateModel(
            name='MaterialCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('수입검사코드', models.CharField(max_length=20)),
                ('검사지침서번호', models.CharField(max_length=20)),
                ('검사일자', models.DateField()),
                ('검사항목', models.CharField(max_length=20)),
                ('판정기준', models.CharField(max_length=20)),
                ('시료크기', models.IntegerField()),
                ('합격수량', models.IntegerField()),
                ('불합격수량', models.IntegerField()),
                ('불합격내용', models.TextField(max_length=100)),
                ('검사자', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='수입검사', to=settings.AUTH_USER_MODEL)),
                ('수입검사의뢰', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualitycontrols.MaterialCheckRegister')),
            ],
            options={
                'verbose_name': '수입검사',
                'verbose_name_plural': '수입검사',
            },
        ),
        migrations.AddField(
            model_name='lowmetarial',
            name='수입검사',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qualitycontrols.MaterialCheck'),
        ),
    ]
