# Generated by Django 2.1.15 on 2020-02-24 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StandardInformation', '0009_auto_20200215_0913'),
        ('qualitycontrols', '0005_auto_20200224_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalcheckregister',
            name='제품',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='최종검사등록', to='StandardInformation.SingleProduct'),
        ),
        migrations.AddField(
            model_name='finalcheckregister',
            name='최종검사코드',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
