# Generated by Django 2.1.15 on 2020-02-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualitycontrols', '0005_auto_20200208_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalcheckregister',
            name='CR',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='FUSE_전_ULUSA',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='LABEL_인쇄물',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='MA',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='MI',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='POWERTRANS',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='Sample방식',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='검사수준',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='결점수',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='기타출하위치',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='내용물',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='전원전압',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lowmetarial',
            name='부적합자재의내용과검토방안',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='lowmetarial',
            name='처리방안',
            field=models.CharField(blank=True, choices=[('재작업', '재작업'), ('수리', '수리'), ('특채(수리후)', '특채(수리후)'), ('특채(무수리)', '특채(무수리)'), ('반품', '반품'), ('폐기', '폐기'), ('기타', '기타')], default='기타', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='materialcheck',
            name='검사항목',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='materialcheck',
            name='불합격내용',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='materialcheck',
            name='판정기준',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='repairregister',
            name='수리내용',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='repairregister',
            name='특이사항',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
