# Generated by Django 2.1.15 on 2020-02-25 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qualitycontrols', '0006_auto_20200224_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairregister',
            name='AS수리의뢰',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='수리내역서', to='afterservices.ASRepairRequest'),
        ),
    ]
