# Generated by Django 2.1.15 on 2020-02-26 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StandardInformation', '0009_auto_20200215_0913'),
        ('qualitycontrols', '0008_repairregister_제품'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalcheck',
            name='제품',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='최종검사', to='StandardInformation.SingleProduct'),
        ),
    ]
