# Generated by Django 2.1.15 on 2020-02-27 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StandardInformation', '0009_auto_20200215_0913'),
        ('qualitycontrols', '0011_auto_20200227_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowmetarial',
            name='자재',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='자재부적합보고서', to='StandardInformation.Material'),
        ),
        migrations.AddField(
            model_name='materialcheck',
            name='자재',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='수입검사', to='StandardInformation.Material'),
        ),
    ]
