# Generated by Django 2.1.15 on 2020-02-27 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qualitycontrols', '0012_auto_20200227_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowmetarial',
            name='수입검사',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='자재부적합보고서', to='qualitycontrols.MaterialCheck'),
        ),
    ]
