# Generated by Django 2.1.15 on 2020-02-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qualitycontrols', '0013_auto_20200227_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lowmetarial',
            old_name='자재부적합보고서번호',
            new_name='자재부적합코드',
        ),
    ]
