# Generated by Django 2.1.15 on 2020-02-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualitycontrols', '0015_auto_20200227_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcheck',
            name='검사일자',
            field=models.DateField(blank=True, null=True),
        ),
    ]
