# Generated by Django 2.1.15 on 2020-02-28 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualitycontrols', '0016_auto_20200227_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalcheckregister',
            name='검시일',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lowmetarial',
            name='검토일',
            field=models.DateField(blank=True, default=datetime.date(2020, 2, 28), null=True),
        ),
    ]
