# Generated by Django 2.1.15 on 2020-04-02 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qualitycontrols', '0035_auto_20200402_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalcheckregister',
            old_name='CR',
            new_name='치명적불량',
        ),
    ]
