# Generated by Django 2.1.15 on 2020-04-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualitycontrols', '0036_auto_20200402_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalcheckregister',
            old_name='MA',
            new_name='경불량',
        ),
        migrations.RenameField(
            model_name='finalcheckregister',
            old_name='MI',
            new_name='샘플링방식',
        ),
        migrations.RenameField(
            model_name='finalcheckregister',
            old_name='Sample방식',
            new_name='중불량',
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='내용물',
            field=models.CharField(blank=True, choices=[('있음', '있음'), ('없음', '없음')], default='있음', max_length=10),
        ),
    ]
