# Generated by Django 2.1.15 on 2020-04-06 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualitycontrols', '0037_auto_20200402_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalcheckregister',
            name='REMARK',
        ),
        migrations.AddField(
            model_name='finalcheckregister',
            name='특이사항',
            field=models.TextField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='FUSE_전_ULUSA',
            field=models.CharField(blank=True, choices=[('31.8mm 1A', '31.8mm 1A'), ('31.8mm 2A', '31.8mm 2A'), ('31.8mm 3A', '31.8mm 3A'), ('31.8mm 4A', '31.8mm 4A'), ('31.8mm 5A', '31.8mm 5A'), ('31.8mm 10A', '31.8mm 10A'), ('31.8mm 15A', '31.8mm 15A'), ('20mm 2A', '20mm 2A'), ('20mm 3.15A', '20mm 3.15A'), ('20mm 5A', '20mm 5A')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='HI_POT_내부검사',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='LABEL_인쇄물',
            field=models.CharField(blank=True, choices=[('후면 좌측', '후면 좌측'), ('후면 우측', '후면 우측'), ('후면 중심', '후면 중심'), ('후면 우측아래', '후면 우측아래'), ('후면 좌측아래', '후면 좌측아래')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='POWERTRANS',
            field=models.CharField(blank=True, choices=[('T-EPD2083-01', 'T-EPD2083-01'), ('T-EPB2032-01', 'T-EPB2032-01'), ('T-EPA2403-01', 'T-EPA2403-01'), ('T-EPA2243-01', 'T-EPA2243-01'), ('T-EPA2123-01', 'T-EPA2123-01'), ('T-EWA2240-01', 'T-EWA2240-01'), ('EWA2120-01', 'EWA2120-01'), ('R-EWA2360-01', 'R-EWA2360-01')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='가_감전압',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='내부검사',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='내압검사',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='내용물',
            field=models.CharField(blank=True, choices=[('있음', '있음'), ('없음', '없음')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='내용물확인',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='동작검사',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='외관검사',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='전원전압',
            field=models.CharField(blank=True, choices=[('DC 24V', 'DC 24V'), ('AC 220V', 'AC 220V')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='포장검사',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lowmetarial',
            name='검토일',
            field=models.DateField(blank=True, default=datetime.date(2020, 4, 6), null=True),
        ),
    ]
