# Generated by Django 2.1.15 on 2020-04-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualitycontrols', '0038_auto_20200406_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalcheckregister',
            name='검사수준',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='결점수',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='경불량',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='샘플링방식',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='중불량',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='치명적불량',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
