# Generated by Django 2.1.15 on 2020-04-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualitycontrols', '0039_auto_20200406_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalcheckregister',
            old_name='내압검사',
            new_name='내압검사_AC',
        ),
        migrations.AddField(
            model_name='finalcheckregister',
            name='내압검사_DC',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NO', 'NO')], max_length=20, null=True),
        ),
    ]
