# Generated by Django 2.1.15 on 2020-04-08 13:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qualitycontrols', '0041_auto_20200407_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalcheckregister',
            name='기본요금',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='finalcheckregister',
            name='동작이상유무',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='finalcheckregister',
            name='발송날짜',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalcheckregister',
            name='발송자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS총괄장발송', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finalcheckregister',
            name='부품비',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='finalcheckregister',
            name='비고',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='finalcheckregister',
            name='수리내역',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='finalcheckregister',
            name='수리비',
            field=models.CharField(blank=True, choices=[('무상', '무상'), ('유상', '유상')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='finalcheckregister',
            name='수리자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS총괄장수리', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finalcheckregister',
            name='외형이상유무',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='finalcheckregister',
            name='입금확인',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalcheckregister',
            name='택배',
            field=models.CharField(blank=True, choices=[('선불', '선불'), ('신용', '신용'), ('착불', '착불')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='finalcheckregister',
            name='특기사항',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='finalcheckregister',
            name='화물',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='HI_POT_내부검사',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='가_감전압',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='부적합수량',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='적합수량',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='특이사항',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='lowmetarial',
            name='검토일',
            field=models.DateField(blank=True, default=datetime.date(2020, 4, 8), null=True),
        ),
    ]
