# Generated by Django 2.1.15 on 2020-04-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualitycontrols', '0042_auto_20200408_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalcheckregister',
            name='동작이상유무',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='비고',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='수리내역',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='수리비',
            field=models.CharField(blank=True, choices=[('무상', '무상'), ('유상', '유상')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='외형이상유무',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='택배',
            field=models.CharField(blank=True, choices=[('선불', '선불'), ('신용', '신용'), ('착불', '착불')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='특기사항',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='화물',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
