# Generated by Django 2.1.15 on 2020-04-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualitycontrols', '0043_auto_20200408_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalcheckregister',
            name='기본요금',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='발송자',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='부품비',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='수리자',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
