# Generated by Django 2.1.15 on 2020-04-08 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qualitycontrols', '0044_auto_20200408_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalcheckregister',
            name='발송자',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS총괄장발송', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='수리자',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS총괄장수리', to=settings.AUTH_USER_MODEL),
        ),
    ]
