# Generated by Django 2.1.15 on 2020-04-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualitycontrols', '0046_auto_20200408_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairregister',
            name='실수리수량',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='repairregister',
            name='폐기수량',
            field=models.IntegerField(null=True),
        ),
    ]
