# Generated by Django 2.1.15 on 2020-04-13 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualitycontrols', '0047_auto_20200408_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialcheck',
            old_name='검사지침서번호',
            new_name='검사지침서',
        ),
        migrations.AlterField(
            model_name='lowmetarial',
            name='검토일',
            field=models.DateField(blank=True, default=datetime.date(2020, 4, 13), null=True),
        ),
    ]
