# Generated by Django 2.1.15 on 2020-04-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualitycontrols', '0048_auto_20200413_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialcheck',
            old_name='불합격내용',
            new_name='부적합내용',
        ),
        migrations.RenameField(
            model_name='materialcheck',
            old_name='불합격수량',
            new_name='부적합수량',
        ),
        migrations.RenameField(
            model_name='materialcheck',
            old_name='합격수량',
            new_name='적합수량',
        ),
        migrations.AlterField(
            model_name='materialcheck',
            name='검사지침서',
            field=models.CharField(blank=True, choices=[('CAE SHI-16-01', 'CAE SHI-16-01'), ('PCB SHI 10-01', 'PCB SHI 10-01'), ('트랜스 SHI 11-06', '트랜스 SHI 11-06'), ('사출 성형품 SHI 16-02', '사출 성형품 SHI 16-02')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='materialcheck',
            name='판정기준',
            field=models.CharField(blank=True, choices=[('AC 0', 'AC 0'), ('Re 1', 'Re 1')], max_length=20, null=True),
        ),
    ]
