# Generated by Django 2.1.15 on 2020-04-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualitycontrols', '0050_auto_20200413_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowmetarial',
            name='첨부파일',
            field=models.FileField(blank=True, null=True, upload_to='lowmaterial'),
        ),
    ]
