# Generated by Django 2.1.15 on 2020-08-27 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualitycontrols', '0066_auto_20200826_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowmetarial',
            name='검토일',
            field=models.DateField(blank=True, default=datetime.date(2020, 8, 27), null=True),
        ),
        migrations.AlterField(
            model_name='materialcheck',
            name='검사지침서',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
