# Generated by Django 2.1.15 on 2020-08-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualitycontrols', '0067_auto_20200827_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcheck',
            name='판정기준',
            field=models.CharField(blank=True, default='AC 0, RE 1', max_length=20, null=True),
        ),
    ]
