# Generated by Django 2.1.15 on 2020-08-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualitycontrols', '0068_auto_20200827_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalcheckregister',
            name='전원전압',
            field=models.CharField(choices=[('DC 24V', 'DC 24V'), ('AC 220V', 'AC 220V')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='materialcheck',
            name='판정기준',
            field=models.CharField(blank=True, default='AC=0, RE=1', max_length=20, null=True),
        ),
    ]
