# Generated by Django 2.1.15 on 2020-09-21 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualitycontrols', '0069_auto_20200827_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalcheckregister',
            name='FUSE_전_ULUSA',
            field=models.CharField(choices=[('31.8mm 1A', '31.8mm 1A'), ('31.8mm 2A', '31.8mm 2A'), ('31.8mm 3A', '31.8mm 3A'), ('31.8mm 4A', '31.8mm 4A'), ('31.8mm 5A', '31.8mm 5A'), ('31.8mm 10A', '31.8mm 10A'), ('31.8mm 15A', '31.8mm 15A'), ('20mm 2A', '20mm 2A'), ('20mm 3.15A', '20mm 3.15A'), ('20mm 5A', '20mm 5A')], default='31.8mm 1A', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='LABEL_인쇄물',
            field=models.CharField(choices=[('후면 좌측', '후면 좌측'), ('후면 우측', '후면 우측'), ('후면 중심', '후면 중심'), ('후면 우측아래', '후면 우측아래'), ('후면 좌측아래', '후면 좌측아래')], default='후면 좌측', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='POWERTRANS',
            field=models.CharField(choices=[('T-EPD2083-01', 'T-EPD2083-01'), ('T-EPB2032-01', 'T-EPB2032-01'), ('T-EPA2403-01', 'T-EPA2403-01'), ('T-EPA2243-01', 'T-EPA2243-01'), ('T-EPA2123-01', 'T-EPA2123-01'), ('T-EWA2240-01', 'T-EWA2240-01'), ('EWA2120-01', 'EWA2120-01'), ('R-EWA2360-01', 'R-EWA2360-01')], default='T-EPD2083-01', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='내부검사',
            field=models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], default='OK', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='내압검사_AC',
            field=models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], default='OK', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='내압검사_DC',
            field=models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], default='OK', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='내용물',
            field=models.CharField(choices=[('있음', '있음'), ('없음', '없음')], default='있음', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='내용물확인',
            field=models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], default='OK', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='동작검사',
            field=models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], default='OK', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='외관검사',
            field=models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], default='OK', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='전원전압',
            field=models.CharField(choices=[('DC 24V', 'DC 24V'), ('AC 220V', 'AC 220V')], default='DC 24V', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalcheckregister',
            name='포장검사',
            field=models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], default='OK', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lowmetarial',
            name='검토일',
            field=models.DateField(blank=True, default=datetime.date(2020, 9, 21), null=True),
        ),
        migrations.AlterField(
            model_name='repairregister',
            name='수리최종',
            field=models.CharField(blank=True, choices=[('최종검사결과', '최종검사결과'), ('AS', 'AS')], default=models.ManyToManyField(null=True, related_name='수리내역서', to='qualitycontrols.FinalCheckRegister'), max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name='repairregister',
            name='최종검사결과',
        ),
        migrations.AddField(
            model_name='repairregister',
            name='최종검사결과',
            field=models.ManyToManyField(null=True, related_name='수리내역서', to='qualitycontrols.FinalCheckRegister'),
        ),
    ]
