# Generated by Django 2.1.15 on 2020-12-27 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('StandardInformation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOfRackProductMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('현재공정', models.CharField(choices=[('배선중', '배선중'), ('소방대기중', '소방대기중'), ('완료', '완료')], default='배선중', max_length=10, null=True)),
                ('제작수량', models.IntegerField()),
                ('랙조립일자', models.DateField(blank=True, null=True)),
                ('특이사항', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': '랙조립',
                'verbose_name_plural': '랙조립',
            },
        ),
        migrations.CreateModel(
            name='StockOfRackProductOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('출하일', models.DateField(null=True)),
                ('출하수량', models.IntegerField(null=True)),
                ('거래명세서첨부', models.FileField(blank=True, help_text='거래명세서를 첨부해주세요.', null=True, upload_to='deal')),
            ],
            options={
                'verbose_name': '랙출하등록',
                'verbose_name_plural': '랙출하등록',
            },
        ),
        migrations.CreateModel(
            name='StockOfRackProductOutRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('수취인', models.CharField(blank=True, max_length=12, null=True)),
                ('수취인주소', models.CharField(blank=True, max_length=100, null=True)),
                ('연락처', models.CharField(blank=True, max_length=50, null=True)),
                ('출하요청수량', models.IntegerField()),
                ('출하요청일', models.DateField(auto_now_add=True)),
                ('출하희망일', models.DateField(blank=True, null=True)),
                ('고객사', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='랙출하요청', to='StandardInformation.Partner')),
                ('랙', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='랙출하요청', to='StandardInformation.RackProduct')),
                ('수주', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='랙출하요청', to='orders.OrderRegister')),
            ],
            options={
                'verbose_name': '랙출하요청',
                'verbose_name_plural': '랙출하요청',
            },
        ),
    ]
