# Generated by Django 2.1.15 on 2020-02-19 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderregister_출하구분'),
        ('stockrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockofrackproductoutrequest',
            name='수주',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='랙출하요청', to='orders.OrderRegister'),
        ),
    ]
