# Generated by Django 2.1.15 on 2020-02-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockrack', '0002_stockofrackproductoutrequest_수주'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockofrackproductoutrequest',
            name='출하요청일',
            field=models.DateField(auto_now_add=True),
        ),
    ]
