# Generated by Django 2.1.15 on 2020-03-24 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StandardInformation', '0014_auto_20200316_2243'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockrack', '0003_auto_20200219_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOfRackProductMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('현재공정', models.CharField(blank=True, choices=[('배선중', '배선중'), ('소방대기완료', '소방대기완료')], max_length=10, null=True)),
                ('제작수량', models.IntegerField()),
                ('랙조립일자', models.DateField(blank=True, null=True)),
                ('특이사항', models.CharField(blank=True, max_length=100, null=True)),
                ('랙', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='랙조립', to='StandardInformation.RackProduct')),
                ('랙조립기사', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='랙조립', to=settings.AUTH_USER_MODEL)),
                ('랙출하요청', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='랙조립', to='stockrack.StockOfRackProductOutRequest')),
            ],
            options={
                'verbose_name': '랙조립',
                'verbose_name_plural': '랙조립',
            },
        ),
    ]
