# Generated by Django 2.1.15 on 2020-04-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockrack', '0008_auto_20200414_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockofrackproductoutrequest',
            old_name='주소',
            new_name='수취인주소',
        ),
    ]
