# Generated by Django 2.1.15 on 2020-12-27 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StandardInformation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOfMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('실수량', models.IntegerField(blank=True, default=0, null=True)),
                ('입고요청포함수량', models.IntegerField(blank=True, default=0, null=True)),
                ('출고요청제외수량', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': '자재재고',
                'verbose_name_plural': '자재재고',
            },
        ),
        migrations.CreateModel(
            name='StockOfMaterialHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('실수량', models.IntegerField(blank=True, default=0, null=True)),
                ('입고요청포함수량', models.IntegerField(blank=True, default=0, null=True)),
                ('출고요청제외수량', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': '자재재고기록용',
                'verbose_name_plural': '자재재고기록용',
            },
        ),
        migrations.CreateModel(
            name='StockOfMaterialIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('입고일', models.DateField(blank=True, null=True)),
                ('입고수량', models.IntegerField(null=True)),
                ('입고유형', models.CharField(choices=[('일반', '일반'), ('반납', '반납')], default='일반', max_length=10, null=True)),
            ],
            options={
                'verbose_name': '자재입고등록',
                'verbose_name_plural': '자재입고등록',
            },
        ),
        migrations.CreateModel(
            name='StockOfMaterialInRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('입고요청수량', models.IntegerField()),
                ('입고요청일', models.DateField()),
                ('입고유형', models.CharField(choices=[('일반', '일반'), ('반납', '반납')], default='일반', max_length=10, null=True)),
            ],
            options={
                'verbose_name': '자재입고요청',
                'verbose_name_plural': '자재입고요청',
            },
        ),
        migrations.CreateModel(
            name='StockOfMaterialOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('출고일', models.DateField(blank=True, null=True)),
                ('출고수량', models.IntegerField(null=True)),
                ('출고유형', models.CharField(choices=[('생산', '생산'), ('AS', 'AS')], default='생산', max_length=10, null=True)),
            ],
            options={
                'verbose_name': '자재출고등록',
                'verbose_name_plural': '자재출고등록',
            },
        ),
        migrations.CreateModel(
            name='StockOfMaterialOutRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('출고요청수량', models.IntegerField()),
                ('출고요청일', models.DateField()),
                ('출고유형', models.CharField(choices=[('생산', '생산'), ('AS', 'AS')], default='생산', max_length=10, null=True)),
                ('자재', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='자재출고요청', to='StandardInformation.Material')),
            ],
            options={
                'verbose_name': '자재출고요청',
                'verbose_name_plural': '자재출고요청',
            },
        ),
    ]
