# Generated by Django 2.1.15 on 2020-02-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockofmaterial',
            name='실수량',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stockofmaterial',
            name='입고요청포함수량',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stockofmaterial',
            name='출고요청제외수량',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stockofmaterialhistory',
            name='실수량',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stockofmaterialhistory',
            name='입고요청포함수량',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stockofmaterialhistory',
            name='출고요청제외수량',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
