# Generated by Django 2.1.15 on 2020-03-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanages', '0002_auto_20200209_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockofmaterialinrequest',
            name='입고유형',
            field=models.CharField(choices=[('일반', '일반'), ('반납', '반납')], default='일반', max_length=10, null=True),
        ),
    ]
