# Generated by Django 2.1.15 on 2020-03-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanages', '0003_stockofmaterialinrequest_입고유형'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockofmaterialoutrequest',
            name='출고유형',
            field=models.CharField(choices=[('생산', '생산'), ('AS', 'AS')], default='생산', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockofmaterialin',
            name='입고일',
            field=models.DateField(blank=True, null=True),
        ),
    ]
