# Generated by Django 2.1.15 on 2020-03-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanages', '0004_auto_20200304_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockofmaterialout',
            name='출고일',
            field=models.DateField(blank=True, null=True),
        ),
    ]
