# Generated by Django 2.1.15 on 2020-04-13 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qualitycontrols', '0050_auto_20200413_1733'),
        ('stockmanages', '0005_auto_20200308_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockofmaterialinrequest',
            name='수입검사',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='자재입고요청', to='qualitycontrols.MaterialCheck'),
        ),
    ]
