# Generated by Django 2.1.15 on 2020-04-13 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanages', '0006_stockofmaterialinrequest_수입검사'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockofmaterialinrequest',
            name='수입검사',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='자재입고요청', to='qualitycontrols.MaterialCheck'),
        ),
    ]
