# Generated by Django 2.1.15 on 2020-12-27 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASRegisters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('접수번호', models.CharField(max_length=20, null=True)),
                ('접수일', models.DateField(blank=True, null=True)),
                ('설치연도', models.DateField(blank=True, null=True)),
                ('접수내용', models.CharField(max_length=100, null=True)),
                ('현장명', models.CharField(max_length=50, null=True)),
                ('주소', models.TextField(blank=True, max_length=120, null=True)),
                ('의뢰자전화번호', models.CharField(blank=True, max_length=20, null=True)),
                ('비용', models.CharField(choices=[('유상', '유상'), ('무상', '무상')], default='유상', max_length=10)),
                ('비고', models.CharField(blank=True, max_length=100, null=True)),
                ('첨부파일', models.FileField(blank=True, null=True, upload_to='ASregister')),
                ('처리방법', models.CharField(choices=[('내부처리', '내부처리'), ('현장방문', '현장방문'), ('접수보류', '접수보류'), ('접수취소', '접수취소'), ('택배수령', '택배수령')], default='담당자연결', max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'AS접수',
                'verbose_name_plural': 'AS접수',
            },
        ),
        migrations.CreateModel(
            name='ASRepairRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('수리요청코드', models.CharField(blank=True, max_length=50, null=True)),
                ('고객성명', models.CharField(blank=True, max_length=50, null=True)),
                ('고객주소', models.TextField(blank=True, max_length=120, null=True)),
                ('고객전화', models.CharField(blank=True, max_length=50, null=True)),
                ('고객팩스', models.CharField(blank=True, max_length=50, null=True)),
                ('AS의뢰내용', models.CharField(blank=True, max_length=50, null=True)),
                ('시리얼번호', models.CharField(blank=True, max_length=50, null=True)),
                ('사용자액세서리', models.CharField(blank=True, max_length=50, null=True)),
                ('택배관련', models.CharField(choices=[('선불', '선불'), ('착불', '착불')], default='선불', max_length=10)),
                ('신청수량', models.IntegerField()),
            ],
            options={
                'verbose_name': 'AS수리요청',
                'verbose_name_plural': 'AS수리요청',
            },
        ),
        migrations.CreateModel(
            name='ASResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('완료날짜', models.DateField(blank=True, null=True)),
                ('완료유형', models.CharField(choices=[('내부처리', '내부처리'), ('담당자내부처리', '담당자내부처리'), ('방문', '방문'), ('재방문', '재방문')], default=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS완료', to='afterservices.ASRegisters'), max_length=10)),
                ('처리내용', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'AS완료',
                'verbose_name_plural': 'AS완료',
            },
        ),
        migrations.CreateModel(
            name='ASReVisitContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('AS날짜', models.DateField(blank=True, null=True)),
                ('AS방법', models.CharField(choices=[('제품수리', '제품수리'), ('제품교체', '제품교체'), ('기타', '기타')], default='제품수리', max_length=10)),
                ('현장명', models.CharField(max_length=50, null=True)),
                ('AS처리내역', models.TextField(null=True)),
                ('특이사항', models.TextField(blank=True, null=True)),
                ('현장택배', models.CharField(blank=True, choices=[('현장', '현장'), ('택배', '택배')], default='현장', max_length=10)),
            ],
            options={
                'verbose_name': 'AS재현장방문',
                'verbose_name_plural': 'AS재현장방문',
            },
        ),
        migrations.CreateModel(
            name='ASVisitContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('AS날짜', models.DateField(blank=True, null=True)),
                ('AS방법', models.CharField(choices=[('수리의뢰', '수리의뢰'), ('자체수리', '자체수리'), ('제품교체', '제품교체'), ('기타', '기타')], default='기타', max_length=10, null=True)),
                ('처리방법', models.CharField(choices=[('자체', '자체'), ('외주', '외주')], default='자체', max_length=10, null=True)),
                ('처리기사', models.CharField(blank=True, max_length=50, null=True)),
                ('견적진행여부', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10, null=True)),
                ('견적서첨부', models.FileField(blank=True, null=True, upload_to='cost')),
                ('특이사항', models.TextField(blank=True, null=True)),
                ('첨부파일', models.FileField(blank=True, null=True, upload_to='ASVisitContents')),
                ('AS접수', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS현장방문', to='afterservices.ASRegisters')),
            ],
            options={
                'verbose_name': 'AS현장방문',
                'verbose_name_plural': 'AS현장방문',
            },
        ),
    ]
