# Generated by Django 2.1.15 on 2020-02-10 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StandardInformation', '0004_auto_20200209_2323'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('afterservices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asregisters',
            options={'verbose_name': 'AS접수', 'verbose_name_plural': 'AS접수'},
        ),
        migrations.AddField(
            model_name='asregisters',
            name='단품',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS등록', to='StandardInformation.SingleProduct'),
        ),
        migrations.AddField(
            model_name='asregisters',
            name='대응유형',
            field=models.CharField(blank=True, choices=[('내부처리', '내부처리'), ('현장방문', '현장방문')], default='내부처리', max_length=10),
        ),
        migrations.AddField(
            model_name='asregisters',
            name='랙',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS등록', to='StandardInformation.RackProduct'),
        ),
        migrations.AddField(
            model_name='asregisters',
            name='방문요청일',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asregisters',
            name='불량분류',
            field=models.CharField(blank=True, choices=[('사용법미숙지', '사용법미숙지'), ('랙구성케이블오류', '랙구성케이블오류'), ('단품불량', '단품불량')], default='사용법미숙지', max_length=10),
        ),
        migrations.AddField(
            model_name='asregisters',
            name='불량분류코드',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='asregisters',
            name='의뢰자전화번호',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='asregisters',
            name='의뢰처',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS등록', to='StandardInformation.CustomerPartner'),
        ),
        migrations.AddField(
            model_name='asregisters',
            name='접수번호',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='asregisters',
            name='접수일',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='asregisters',
            name='접수자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS등록', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asregisters',
            name='접수제품분류',
            field=models.CharField(blank=True, choices=[('단품', '단품'), ('랙', '랙')], default='단품', max_length=10),
        ),
        migrations.AddField(
            model_name='asregisters',
            name='현상',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
