# Generated by Django 2.1.15 on 2020-02-10 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('afterservices', '0002_auto_20200210_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asresults',
            options={'verbose_name': 'AS완료', 'verbose_name_plural': 'AS완료'},
        ),
        migrations.AlterModelOptions(
            name='asrevisitcontents',
            options={'verbose_name': 'AS현장방문', 'verbose_name_plural': 'AS현장방문'},
        ),
        migrations.AlterModelOptions(
            name='asvisitcontents',
            options={'verbose_name': 'AS현장방문', 'verbose_name_plural': 'AS현장방문'},
        ),
        migrations.AlterModelOptions(
            name='asvisitrequests',
            options={'verbose_name': 'AS현장방문요청', 'verbose_name_plural': 'AS현장방문요청'},
        ),
        migrations.AddField(
            model_name='asresults',
            name='내부처리',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS완료', to='afterservices.ASRegisters'),
        ),
        migrations.AddField(
            model_name='asresults',
            name='완료날짜',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asresults',
            name='완료유형',
            field=models.CharField(blank=True, choices=[('내부처리', '내부처리'), ('제품취소', '제품취소'), ('재방문', '재방문')], default=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS완료', to='afterservices.ASRegisters'), max_length=10),
        ),
        migrations.AddField(
            model_name='asresults',
            name='완료확인자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS완료', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asresults',
            name='재방문',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS완료', to='afterservices.ASReVisitContents'),
        ),
        migrations.AddField(
            model_name='asresults',
            name='제품취소',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS완료', to='afterservices.ASVisitContents'),
        ),
        migrations.AddField(
            model_name='asrevisitcontents',
            name='AS날짜',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asrevisitcontents',
            name='AS방법',
            field=models.CharField(blank=True, choices=[('제품수리', '제품수리'), ('제품교체', '제품교체'), ('기타', '기타')], default='제품수리', max_length=10),
        ),
        migrations.AddField(
            model_name='asrevisitcontents',
            name='AS처리내역',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='asrevisitcontents',
            name='고객이름',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asrevisitcontents',
            name='재방문여부',
            field=models.CharField(blank=True, choices=[('완료', '완료'), ('재방문', '재방문')], default='완료', max_length=10),
        ),
        migrations.AddField(
            model_name='asrevisitcontents',
            name='전AS현장방문',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS재방문', to='afterservices.ASVisitContents'),
        ),
        migrations.AddField(
            model_name='asrevisitcontents',
            name='특이사항',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='asvisitcontents',
            name='AS날짜',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asvisitcontents',
            name='AS방법',
            field=models.CharField(blank=True, choices=[('제품수리', '제품수리'), ('제품교체', '제품교체'), ('제품취소', '제품취소'), ('기타', '기타')], default='제품수리', max_length=10),
        ),
        migrations.AddField(
            model_name='asvisitcontents',
            name='AS처리내역',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='asvisitcontents',
            name='AS현장방문요청',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS현장방문', to='afterservices.ASVisitRequests'),
        ),
        migrations.AddField(
            model_name='asvisitcontents',
            name='고객이름',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asvisitcontents',
            name='재방문여부',
            field=models.CharField(blank=True, choices=[('완료', '완료'), ('재방문', '재방문')], default='완료', max_length=10),
        ),
        migrations.AddField(
            model_name='asvisitcontents',
            name='특이사항',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='asvisitrequests',
            name='AS담당자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS현장방문요청', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asvisitrequests',
            name='AS접수',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS현장방문요청', to='afterservices.ASRegisters'),
        ),
    ]
