# Generated by Django 2.1.15 on 2020-02-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0003_auto_20200210_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asrevisitcontents',
            options={'verbose_name': 'AS재현장방문', 'verbose_name_plural': 'AS재현장방문'},
        ),
        migrations.RemoveField(
            model_name='asrevisitcontents',
            name='재방문여부',
        ),
        migrations.AlterField(
            model_name='asrevisitcontents',
            name='특이사항',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asvisitcontents',
            name='특이사항',
            field=models.TextField(blank=True, null=True),
        ),
    ]
