# Generated by Django 2.1.15 on 2020-02-25 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StandardInformation', '0009_auto_20200215_0913'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('afterservices', '0005_auto_20200210_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASRepairRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('신청수량', models.IntegerField()),
                ('AS현장방문', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS수리요청', to='afterservices.ASVisitContents')),
                ('신청자', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS수리요청', to=settings.AUTH_USER_MODEL)),
                ('신청품목', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS수리요청', to='StandardInformation.SingleProduct')),
            ],
            options={
                'verbose_name': 'AS수리요청',
                'verbose_name_plural': 'AS수리요청',
            },
        ),
    ]
