# Generated by Django 2.1.15 on 2020-02-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0006_asrepairrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='asrepairrequest',
            name='수리요청코드',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
