# Generated by Django 2.1.15 on 2020-02-28 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0007_asrepairrequest_수리요청코드'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asvisitcontents',
            name='AS현장방문요청',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS현장방문', to='afterservices.ASVisitRequests'),
        ),
    ]
