# Generated by Django 2.1.15 on 2020-02-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0008_auto_20200228_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asregisters',
            name='의뢰자전화번호',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
