# Generated by Django 2.1.15 on 2020-02-28 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0009_auto_20200228_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asrevisitcontents',
            name='전AS현장방문',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS재방문', to='afterservices.ASVisitContents'),
        ),
    ]
