# Generated by Django 2.1.15 on 2020-02-29 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0011_auto_20200228_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asregisters',
            name='대응유형',
            field=models.CharField(choices=[('내부처리', '내부처리'), ('현장방문', '현장방문')], default='내부처리', max_length=10),
        ),
        migrations.AlterField(
            model_name='asregisters',
            name='불량분류',
            field=models.CharField(choices=[('사용법미숙지', '사용법미숙지'), ('랙구성케이블오류', '랙구성케이블오류'), ('단품불량', '단품불량')], default='사용법미숙지', max_length=10),
        ),
        migrations.AlterField(
            model_name='asregisters',
            name='의뢰자전화번호',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='asregisters',
            name='접수일',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asregisters',
            name='접수제품분류',
            field=models.CharField(choices=[('단품', '단품'), ('랙', '랙')], default='단품', max_length=10),
        ),
        migrations.AlterField(
            model_name='asvisitrequests',
            name='AS접수',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS현장방문요청', to='afterservices.ASRegisters'),
        ),
    ]
