# Generated by Django 2.1.15 on 2020-02-29 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0012_auto_20200229_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asresults',
            name='내부처리',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS완료', to='afterservices.ASRegisters'),
        ),
        migrations.AlterField(
            model_name='asresults',
            name='완료유형',
            field=models.CharField(choices=[('내부처리', '내부처리'), ('제품취소', '제품취소'), ('재방문', '재방문')], default=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS완료', to='afterservices.ASRegisters'), max_length=10),
        ),
        migrations.AlterField(
            model_name='asresults',
            name='재방문',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS완료', to='afterservices.ASReVisitContents'),
        ),
        migrations.AlterField(
            model_name='asresults',
            name='제품취소',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS완료', to='afterservices.ASVisitContents'),
        ),
    ]
