# Generated by Django 2.1.15 on 2020-03-02 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0013_auto_20200229_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asvisitrequests',
            name='AS접수',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AS현장방문요청', to='afterservices.ASRegisters'),
        ),
    ]
