# Generated by Django 2.1.15 on 2020-03-02 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0014_auto_20200302_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asresults',
            old_name='제품취소',
            new_name='방문',
        ),
        migrations.AlterField(
            model_name='asresults',
            name='완료유형',
            field=models.CharField(choices=[('내부처리', '내부처리'), ('방문', '방문'), ('재방문', '재방문')], default=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS완료', to='afterservices.ASRegisters'), max_length=10),
        ),
    ]
