# Generated by Django 2.1.15 on 2020-03-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0015_auto_20200302_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asrevisitcontents',
            name='AS방법',
            field=models.CharField(choices=[('제품수리', '제품수리'), ('제품교체', '제품교체'), ('기타', '기타')], default='제품수리', max_length=10),
        ),
        migrations.AlterField(
            model_name='asvisitcontents',
            name='AS방법',
            field=models.CharField(choices=[('제품수리', '제품수리'), ('제품교체', '제품교체'), ('제품취소', '제품취소'), ('기타', '기타')], default='제품수리', max_length=10),
        ),
        migrations.AlterField(
            model_name='asvisitcontents',
            name='재방문여부',
            field=models.CharField(choices=[('완료', '완료'), ('재방문', '재방문')], default='완료', max_length=10),
        ),
    ]
