# Generated by Django 2.1.15 on 2020-03-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0016_auto_20200303_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='asregisters',
            name='현장명',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
