# Generated by Django 2.1.15 on 2020-04-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0017_asregisters_현장명'),
    ]

    operations = [
        migrations.AddField(
            model_name='asrepairrequest',
            name='고객성명',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asrepairrequest',
            name='고객전화',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asrepairrequest',
            name='고객주소',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='asrepairrequest',
            name='사용자액세서리',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asrepairrequest',
            name='시리얼번호',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asrepairrequest',
            name='택배관련',
            field=models.CharField(blank=True, choices=[('선불', '선불'), ('착불', '착불')], default='선불', max_length=10, null=True),
        ),
    ]
