# Generated by Django 2.1.15 on 2020-04-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0018_auto_20200407_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asrepairrequest',
            name='택배관련',
            field=models.CharField(blank=True, choices=[('선불', '선불'), ('착불', '착불')], default='선불', max_length=10),
        ),
    ]
