# Generated by Django 2.1.15 on 2020-04-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0019_auto_20200407_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='asrepairrequest',
            name='고객팩스',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asrepairrequest',
            name='택배관련',
            field=models.CharField(choices=[('선불', '선불'), ('착불', '착불')], default='선불', max_length=10),
        ),
    ]
