# Generated by Django 2.1.15 on 2020-04-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0020_auto_20200407_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='asrepairrequest',
            name='AS의뢰내용',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
