# Generated by Django 2.1.15 on 2020-04-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0021_asrepairrequest_as의뢰내용'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asregisters',
            name='불량분류',
            field=models.CharField(max_length=30),
        ),
    ]
