# Generated by Django 2.1.15 on 2020-04-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0022_auto_20200415_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='asregisters',
            name='접수보류',
            field=models.CharField(choices=[('진행', '진행'), ('접수보류', '접수보류')], default='진행', max_length=10),
        ),
    ]
