# Generated by Django 2.1.15 on 2020-04-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0023_asregisters_접수보류'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asregisters',
            name='대응유형',
            field=models.CharField(choices=[('내부처리', '내부처리'), ('현장방문', '현장방문'), ('진행', '진행'), ('접수보류', '접수보류')], default='내부처리', max_length=10),
        ),
    ]
