# Generated by Django 2.1.15 on 2020-04-16 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0024_auto_20200416_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='asresults',
            name='담당자내부처리',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS완료', to='afterservices.ASVisitRequests'),
        ),
        migrations.AlterField(
            model_name='asregisters',
            name='대응유형',
            field=models.CharField(choices=[('내부처리', '내부처리'), ('담당자연결', '담당자연결')], default='내부처리', max_length=10),
        ),
        migrations.AlterField(
            model_name='asresults',
            name='완료유형',
            field=models.CharField(choices=[('내부처리', '내부처리'), ('담당자내부처리', '담당자내부처리'), ('방문', '방문'), ('재방문', '재방문')], default=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS완료', to='afterservices.ASRegisters'), max_length=10),
        ),
    ]
