# Generated by Django 2.1.15 on 2020-04-16 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0025_auto_20200416_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asregisters',
            old_name='접수보류',
            new_name='인계후',
        ),
    ]
