# Generated by Django 2.1.15 on 2020-04-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0026_auto_20200416_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asregisters',
            name='인계후',
            field=models.CharField(choices=[('현장방문', '현장방문'), ('내부처리', '내부처리'), ('접수보류', '접수보류'), ('접수취소', '접수취소')], default='진행', max_length=10),
        ),
    ]
