# Generated by Django 2.1.15 on 2020-04-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0027_auto_20200416_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='asresults',
            name='처리내용',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asregisters',
            name='인계후',
            field=models.CharField(choices=[('현장방문', '현장방문'), ('내부처리', '내부처리'), ('접수보류', '접수보류'), ('접수취소', '접수취소')], default='현장방문', max_length=10),
        ),
        migrations.AlterField(
            model_name='asvisitcontents',
            name='재방문여부',
            field=models.CharField(choices=[('완료', '완료'), ('재방문', '재방문'), ('견적진행', '견적진행')], default='완료', max_length=10),
        ),
    ]
