# Generated by Django 2.1.15 on 2020-04-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0031_auto_20200417_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asregisters',
            name='인계후',
            field=models.CharField(choices=[('내부처리', '내부처리'), ('현장방문', '현장방문'), ('접수보류', '접수보류'), ('접수취소', '접수취소')], default='', max_length=10, null=True),
        ),
    ]
