# Generated by Django 2.1.15 on 2020-06-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0033_asregisters_비용'),
    ]

    operations = [
        migrations.AddField(
            model_name='asvisitcontents',
            name='처리기사',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asvisitcontents',
            name='처리회사',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asregisters',
            name='대응유형',
            field=models.CharField(blank=True, choices=[('내부처리', '내부처리'), ('담당자연결', '담당자연결')], default='담당자연결', max_length=10),
        ),
        migrations.AlterField(
            model_name='asvisitcontents',
            name='고객이름',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
