# Generated by Django 2.1.15 on 2020-06-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0034_auto_20200612_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asregisters',
            name='대응유형',
            field=models.CharField(blank=True, choices=[('내부처리', '내부처리'), ('담당자연결', '담당자연결')], default='담당자연결', max_length=10, null=True),
        ),
    ]
