# Generated by Django 2.1.15 on 2020-06-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0035_auto_20200612_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='asvisitcontents',
            name='하자파일',
            field=models.FileField(blank=True, null=True, upload_to='bad'),
        ),
    ]
