# Generated by Django 2.1.15 on 2020-06-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0036_asvisitcontents_하자파일'),
    ]

    operations = [
        migrations.AddField(
            model_name='asvisitcontents',
            name='견적서',
            field=models.FileField(blank=True, null=True, upload_to='cost'),
        ),
    ]
