# Generated by Django 2.1.15 on 2020-11-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0038_auto_20201113_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='asregisters',
            name='설치연도',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asregisters',
            name='주소',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='asregisters',
            name='첨부파일',
            field=models.FileField(blank=True, null=True, upload_to='cost'),
        ),
    ]
