# Generated by Django 2.1.15 on 2020-11-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0039_auto_20201113_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='asregisters',
            name='비고',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asregisters',
            name='불량분류',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='asregisters',
            name='첨부파일',
            field=models.FileField(blank=True, null=True, upload_to='ASregister'),
        ),
    ]
