# Generated by Django 2.1.15 on 2020-11-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0041_auto_20201113_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='asregisters',
            name='접수내용',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
