# Generated by Django 2.1.15 on 2020-11-26 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0042_asregisters_접수내용'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asregisters',
            name='현상',
        ),
    ]
