# Generated by Django 2.1.15 on 2020-11-26 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0043_remove_asregisters_현상'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asregisters',
            old_name='대응유형',
            new_name='처리방법',
        ),
    ]
