# Generated by Django 2.1.15 on 2020-12-02 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0045_auto_20201126_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asvisitrequests',
            name='AS담당자',
        ),
        migrations.RemoveField(
            model_name='asvisitrequests',
            name='AS접수',
        ),
        migrations.RemoveField(
            model_name='asresults',
            name='담당자내부처리',
        ),
        migrations.AlterField(
            model_name='asregisters',
            name='처리방법',
            field=models.CharField(choices=[('내부처리', '내부처리'), ('현장방문', '현장방문'), ('접수보류', '접수보류'), ('접수취소', '접수취소'), ('택배수령', '택배수령')], default='담당자연결', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='asvisitcontents',
            name='AS현장방문요청',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS현장방문', to='afterservices.ASRegisters'),
        ),
        migrations.DeleteModel(
            name='ASVisitRequests',
        ),
    ]
