# Generated by Django 2.1.15 on 2020-12-02 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0046_auto_20201202_0328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asvisitcontents',
            old_name='AS현장방문요청',
            new_name='AS접수',
        ),
    ]
