# Generated by Django 2.1.15 on 2020-12-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0047_auto_20201202_0343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asvisitcontents',
            old_name='견적서',
            new_name='견적서첨부',
        ),
        migrations.RemoveField(
            model_name='asvisitcontents',
            name='AS처리내역',
        ),
        migrations.RemoveField(
            model_name='asvisitcontents',
            name='고객이름',
        ),
        migrations.RemoveField(
            model_name='asvisitcontents',
            name='단품',
        ),
        migrations.RemoveField(
            model_name='asvisitcontents',
            name='랙',
        ),
        migrations.RemoveField(
            model_name='asvisitcontents',
            name='재방문여부',
        ),
        migrations.RemoveField(
            model_name='asvisitcontents',
            name='접수제품분류',
        ),
        migrations.RemoveField(
            model_name='asvisitcontents',
            name='처리회사',
        ),
        migrations.RemoveField(
            model_name='asvisitcontents',
            name='하자파일',
        ),
        migrations.AddField(
            model_name='asvisitcontents',
            name='견적진행여부',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='asvisitcontents',
            name='처리방법',
            field=models.CharField(choices=[('자체', '자체'), ('외주', '외주')], default='자체', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='asvisitcontents',
            name='첨부파일',
            field=models.FileField(blank=True, null=True, upload_to='ASVisitContents'),
        ),
        migrations.AlterField(
            model_name='asvisitcontents',
            name='AS방법',
            field=models.CharField(choices=[('수리의뢰', '수리의뢰'), ('자체수리', '자체수리'), ('제품교체', '제품교체'), ('기타', '기타')], default='기타', max_length=10, null=True),
        ),
    ]
