# Generated by Django 2.1.15 on 2020-12-02 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0048_auto_20201202_0402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asvisitcontents',
            old_name='처리기사',
            new_name='입력자',
        ),
    ]
