# Generated by Django 2.1.15 on 2020-12-02 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0049_auto_20201202_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asvisitcontents',
            name='수리기사',
        ),
        migrations.AddField(
            model_name='asvisitcontents',
            name='처리기사',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asvisitcontents',
            name='입력자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AS현장방문', to=settings.AUTH_USER_MODEL),
        ),
    ]
