# Generated by Django 2.1.15 on 2020-12-08 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0051_auto_20201208_0709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asrevisitcontents',
            old_name='고객이름',
            new_name='현장명',
        ),
    ]
