# Generated by Django 2.1.15 on 2020-12-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterservices', '0052_auto_20201208_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asregisters',
            name='비고',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
