# Generated by Django 2.1.15 on 2020-02-09 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialApplyRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('작성일', models.DateField()),
                ('특채발행번호', models.CharField(max_length=50)),
                ('특채발행일', models.DateField()),
                ('제품코드', models.CharField(max_length=50)),
                ('폐기시손실액', models.IntegerField()),
                ('특채신청수량', models.IntegerField()),
                ('불량내용', models.TextField()),
                ('사용가능사유', models.TextField()),
                ('특채관련회의록첨부', models.FileField(blank=True, null=True, upload_to='')),
                ('수주', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='특채신청등록', to='orders.OrderRegister')),
                ('작성자', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='특채신청등록', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '특채신청등록',
                'verbose_name_plural': '특채신청등록',
            },
        ),
    ]
