# Generated by Django 2.1.15 on 2020-12-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialApplyRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('작성일', models.DateField()),
                ('특채발행번호', models.CharField(max_length=50)),
                ('특채발행일', models.DateField()),
                ('폐기시손실액', models.IntegerField()),
                ('특채신청수량', models.IntegerField()),
                ('불량내용', models.TextField()),
                ('사용가능사유', models.TextField()),
                ('특채관련회의록첨부', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': '특채신청등록',
                'verbose_name_plural': '특채신청등록',
            },
        ),
        migrations.CreateModel(
            name='SpecialConductRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('특채수량중납품수량', models.IntegerField()),
            ],
            options={
                'verbose_name': '특채처리',
                'verbose_name_plural': '특채처리',
            },
        ),
        migrations.CreateModel(
            name='SpecialRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('특채등록일', models.DateField()),
                ('특채수량', models.IntegerField()),
            ],
            options={
                'verbose_name': '특채등록',
                'verbose_name_plural': '특채등록',
            },
        ),
        migrations.CreateModel(
            name='SpecialRejectRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('특채반품수량', models.IntegerField()),
            ],
            options={
                'verbose_name': '특채반품',
                'verbose_name_plural': '특채반품',
            },
        ),
    ]
