# Generated by Django 2.1.15 on 2020-02-09 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialapplyregister',
            name='제품코드',
        ),
    ]
