# Generated by Django 2.1.15 on 2020-12-27 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StandardInformation', '0002_auto_20201227_1834'),
        ('specials', '0001_initial'),
        ('orders', '0002_auto_20201227_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialrejectregister',
            name='작성자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='특채반품', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialrejectregister',
            name='특채처리',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='특채반품', to='specials.SpecialConductRegister'),
        ),
        migrations.AddField(
            model_name='specialregister',
            name='특채등록자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='특채등록', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialregister',
            name='특채신청등록',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='특채등록', to='specials.SpecialApplyRegister'),
        ),
        migrations.AddField(
            model_name='specialconductregister',
            name='작성자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='특채처리', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialconductregister',
            name='특채',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='특채처리', to='specials.SpecialRegister'),
        ),
        migrations.AddField(
            model_name='specialapplyregister',
            name='고객사',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='특채신청등록', to='StandardInformation.CustomerPartner'),
        ),
        migrations.AddField(
            model_name='specialapplyregister',
            name='수주',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='특채신청등록', to='orders.OrderRegister'),
        ),
        migrations.AddField(
            model_name='specialapplyregister',
            name='작성자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='특채신청등록', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialapplyregister',
            name='제품',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='특채신청등록', to='StandardInformation.SingleProduct'),
        ),
    ]
