# Generated by Django 2.1.15 on 2020-02-09 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0003_specialregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialConductRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('특채수량중납품수량', models.IntegerField()),
                ('특채', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='특채처리', to='specials.SpecialRegister')),
            ],
            options={
                'verbose_name': '특채처리',
                'verbose_name_plural': '특채처리',
            },
        ),
        migrations.CreateModel(
            name='SpecialRejectRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('특채반품수량', models.IntegerField()),
                ('특채처리', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='특채처리', to='specials.SpecialConductRegister')),
            ],
            options={
                'verbose_name': '특채반품',
                'verbose_name_plural': '특채반품',
            },
        ),
    ]
