# Generated by Django 2.1.15 on 2020-03-12 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StandardInformation', '0012_measure_작성자'),
        ('specials', '0005_specialapplyregister_제품'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialapplyregister',
            name='고객사',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='특채신청등록', to='StandardInformation.CustomerPartner'),
        ),
    ]
