# Generated by Django 2.1.15 on 2020-03-13 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0006_specialapplyregister_고객사'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialrejectregister',
            name='특채처리',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='특채반품', to='specials.SpecialConductRegister'),
        ),
    ]
