# Generated by Django 2.1.15 on 2020-03-13 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specials', '0007_auto_20200313_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialrejectregister',
            name='작성자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='특채반품', to=settings.AUTH_USER_MODEL),
        ),
    ]
