# Generated by Django 2.1.15 on 2020-03-14 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specials', '0008_specialrejectregister_작성자'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialconductregister',
            name='작성자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='특채처리', to=settings.AUTH_USER_MODEL),
        ),
    ]
