# Generated by Django 2.1.15 on 2020-02-09 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StandardInformation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOfSingleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('실수량', models.IntegerField(blank=True, null=True)),
                ('입고요청포함수량', models.IntegerField(blank=True, null=True)),
                ('출하요청제외수량', models.IntegerField(blank=True, null=True)),
                ('단품', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='단품재고', to='StandardInformation.SingleProduct')),
            ],
            options={
                'verbose_name': '단품재고',
                'verbose_name_plural': '단품재고',
            },
        ),
        migrations.CreateModel(
            name='StockOfSingleProductHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('실수량', models.IntegerField(blank=True, null=True)),
                ('입고요청포함수량', models.IntegerField(blank=True, null=True)),
                ('출하요청제외수량', models.IntegerField(blank=True, null=True)),
                ('단품', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='단품재고기록', to='StandardInformation.SingleProduct')),
            ],
            options={
                'verbose_name': '단품재고기록용',
                'verbose_name_plural': '단품재고기록용',
            },
        ),
        migrations.CreateModel(
            name='StockOfSingleProductIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('입고일', models.DateField(null=True)),
                ('입고수량', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': '단품입고등록',
                'verbose_name_plural': '단품입고등록',
            },
        ),
        migrations.CreateModel(
            name='StockOfSingleProductInRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('입고요청수량', models.IntegerField()),
                ('입고요청일', models.DateField()),
                ('단품', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='단품입고요청', to='StandardInformation.SingleProduct')),
                ('입고요청자', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='단품입고요청', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '단품입고요청',
                'verbose_name_plural': '단품입고요청',
            },
        ),
        migrations.CreateModel(
            name='StockOfSingleProductOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('출하일', models.DateField(null=True)),
                ('출하수량', models.IntegerField(null=True)),
                ('거래명세서첨부', models.FileField(blank=True, help_text='거래명세서를 첨부해주세요.', null=True, upload_to='deal')),
                ('고객사', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='단품출하', to='StandardInformation.CustomerPartner')),
            ],
            options={
                'verbose_name': '단품출하등록',
                'verbose_name_plural': '단품출하등록',
            },
        ),
        migrations.CreateModel(
            name='StockOfSingleProductOutRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('출하요청수량', models.IntegerField()),
                ('출하요청일', models.DateField()),
                ('단품', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='단품출하요청', to='StandardInformation.SingleProduct')),
                ('출하요청자', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='단품출하요청', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '단품출하요청',
                'verbose_name_plural': '단품출하요청',
            },
        ),
        migrations.AddField(
            model_name='stockofsingleproductout',
            name='단품출하요청',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='단품출하등록', to='stocksingle.StockOfSingleProductOutRequest'),
        ),
        migrations.AddField(
            model_name='stockofsingleproductout',
            name='출하자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='단품출하등록', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockofsingleproductin',
            name='단품입고요청',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='단품입고등록', to='stocksingle.StockOfSingleProductInRequest'),
        ),
        migrations.AddField(
            model_name='stockofsingleproductin',
            name='입고자',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='단품입고등록', to=settings.AUTH_USER_MODEL),
        ),
    ]
