# Generated by Django 2.1.15 on 2020-02-09 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StandardInformation', '0003_auto_20200209_1734'),
        ('stocksingle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockofsingleproductout',
            name='고객사',
        ),
        migrations.AddField(
            model_name='stockofsingleproductoutrequest',
            name='고객사',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='단품출하요청', to='StandardInformation.CustomerPartner'),
        ),
        migrations.AddField(
            model_name='stockofsingleproductoutrequest',
            name='출하희망일',
            field=models.DateField(blank=True, null=True),
        ),
    ]
