# Generated by Django 2.1.15 on 2020-02-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksingle', '0002_auto_20200209_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockofsingleproduct',
            name='실수량',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stockofsingleproduct',
            name='입고요청포함수량',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stockofsingleproduct',
            name='출하요청제외수량',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stockofsingleproducthistory',
            name='실수량',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stockofsingleproducthistory',
            name='입고요청포함수량',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stockofsingleproducthistory',
            name='출하요청제외수량',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
