# Generated by Django 2.1.15 on 2020-02-19 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocksingle', '0004_auto_20200210_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockofsingleproductoutrequest',
            name='AS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='단품출하요청', to='afterservices.ASVisitContents'),
        ),
        migrations.AlterField(
            model_name='stockofsingleproductoutrequest',
            name='단품',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='단품출하요청', to='StandardInformation.SingleProduct'),
        ),
        migrations.AlterField(
            model_name='stockofsingleproductoutrequest',
            name='수주',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='단품출하요청', to='orders.OrderRegister'),
        ),
        migrations.AlterField(
            model_name='stockofsingleproductoutrequest',
            name='출하요청일',
            field=models.DateField(auto_now_add=True),
        ),
    ]
