# Generated by Django 2.1.15 on 2020-03-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksingle', '0005_auto_20200219_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockofsingleproductoutrequest',
            name='수주AS',
            field=models.CharField(blank=True, choices=[('수주', '수주'), ('AS', 'AS')], default='수주', max_length=10, null=True),
        ),
    ]
