# Generated by Django 2.1.15 on 2020-03-23 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200308_2202'),
        ('stocksingle', '0006_stockofsingleproductoutrequest_수주as'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockofsingleproductinrequest',
            name='수주',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='단품입고요청', to='orders.OrderRegister'),
        ),
    ]
