# Generated by Django 2.1.15 on 2020-03-23 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocksingle', '0007_stockofsingleproductinrequest_수주'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockofsingleproductinrequest',
            name='출하요청',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='단품입고요청', to='stocksingle.StockOfSingleProductOutRequest'),
        ),
    ]
