# Generated by Django 2.1.15 on 2020-03-24 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockrack', '0003_auto_20200219_1748'),
        ('stocksingle', '0008_stockofsingleproductinrequest_출하요청'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockofsingleproductinrequest',
            name='랙출하요청',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='단품입고요청', to='stockrack.StockOfRackProductOutRequest'),
        ),
    ]
