# Generated by Django 2.1.15 on 2020-04-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksingle', '0009_stockofsingleproductinrequest_랙출하요청'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockofsingleproductoutrequest',
            name='수취인',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='stockofsingleproductoutrequest',
            name='연락처',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stockofsingleproductoutrequest',
            name='주소',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
