# Generated by Django 2.1.15 on 2020-12-09 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocksingle', '0011_auto_20200414_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockofsingleproductoutrequest',
            name='고객사',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='단품출하요청', to='StandardInformation.Partner'),
        ),
    ]
