# Generated by Django 2.1.15 on 2020-12-27 18:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyProduceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('수량', models.IntegerField(null=True)),
                ('작성일', models.DateField(null=True)),
            ],
            options={
                'verbose_name': '월별생산계획',
                'verbose_name_plural': '월별생산계획',
            },
        ),
        migrations.CreateModel(
            name='ProduceRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('생산계획등록코드', models.CharField(max_length=50)),
                ('현재공정', models.CharField(choices=[('예비작업', '예비작업'), ('조립', '조립'), ('검사', '검사')], default='예비작업', max_length=10, null=True)),
                ('현재공정달성율', models.CharField(choices=[('0%', '0%'), ('25%', '25%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], default='0%', max_length=10, null=True)),
                ('계획생산량', models.IntegerField(null=True)),
                ('일일생산량', models.IntegerField(null=True)),
                ('누적생산량', models.IntegerField(blank=True, null=True)),
                ('특이사항', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': '생산계획등록',
                'verbose_name_plural': '생산계획등록',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('수리생산', models.CharField(choices=[('생산계획', '생산계획'), ('AS', 'AS')], default=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='작업지시서', to='producemanages.ProduceRegister'), max_length=10, null=True)),
                ('작업지시코드', models.CharField(max_length=30, null=True)),
                ('수량', models.IntegerField(null=True)),
                ('특이사항', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': '작업지시서',
                'verbose_name_plural': '작업지시서',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('생산일시', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('생산수량', models.IntegerField(null=True)),
                ('특이사항', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': '작업지시서등록',
                'verbose_name_plural': '작업지시서등록',
            },
        ),
    ]
