# Generated by Django 2.1.15 on 2020-02-10 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producemanages', '0002_auto_20200210_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='수리생산',
            field=models.CharField(blank=True, choices=[('생산계획', '생산계획'), ('AS', 'AS')], default=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='작업지시서', to='producemanages.ProduceRegister'), max_length=10, null=True),
        ),
    ]
