# Generated by Django 2.1.15 on 2020-02-08 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producemanages', '0002_delete_repairregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderregister',
            name='생산일시',
            field=models.DateField(default=datetime.date(2020, 2, 8)),
        ),
    ]
