# Generated by Django 2.1.15 on 2020-02-10 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producemanages', '0004_auto_20200210_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='rev1',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='rev2',
        ),
        migrations.AlterField(
            model_name='workorderregister',
            name='작업지시서',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='작업지시서등록', to='producemanages.WorkOrder'),
        ),
    ]
