# Generated by Django 2.1.15 on 2020-02-16 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producemanages', '0009_auto_20200216_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produceregister',
            name='생산의뢰',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='생산계획', to='orders.OrderProduce'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='생산계획',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='작업지시서', to='producemanages.ProduceRegister'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='수리생산',
            field=models.CharField(blank=True, choices=[('생산계획', '생산계획'), ('AS', 'AS')], default=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='작업지시서', to='producemanages.ProduceRegister'), max_length=10, null=True),
        ),
    ]
