# Generated by Django 2.1.15 on 2020-02-17 19:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producemanages', '0010_auto_20200216_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='생산계획',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='작업지시서', to='producemanages.ProduceRegister'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='수리생산',
            field=models.CharField(choices=[('생산계획', '생산계획'), ('AS', 'AS')], default=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='작업지시서', to='producemanages.ProduceRegister'), max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='workorderregister',
            name='생산일시',
            field=models.DateField(default=datetime.date(2020, 2, 17)),
        ),
    ]
