# Generated by Django 2.1.15 on 2020-02-26 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producemanages', '0017_auto_20200225_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produceregister',
            name='현재공정',
            field=models.CharField(choices=[('예비작업', '예비작업'), ('조립', '조립'), ('검사', '검사')], default='예비작업', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='produceregister',
            name='현재공정달성율',
            field=models.CharField(choices=[('0%', '0%'), ('25%', '25%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], default='0%', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='workorderregister',
            name='생산일시',
            field=models.DateField(blank=True, default=datetime.date(2020, 2, 26), null=True),
        ),
    ]
