# Generated by Django 2.1.15 on 2020-03-30 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StandardInformation', '0014_auto_20200316_2243'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producemanages', '0036_auto_20200330_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyProduceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('수량', models.IntegerField(null=True)),
                ('단품모델', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='월별생산계획', to='StandardInformation.SingleProduct')),
                ('작성자', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='월별생산계획', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '월별생산계획',
                'verbose_name_plural': '월별생산계획',
            },
        ),
    ]
