# Generated by Django 2.1.15 on 2020-03-31 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producemanages', '0038_auto_20200331_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyproducelist',
            name='단품모델',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='월별생산계획', to='StandardInformation.SingleProduct'),
        ),
    ]
