# Generated by Django 2.1.15 on 2020-02-09 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StandardInformation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('생산의뢰코드', models.CharField(max_length=50)),
                ('긴급도', models.CharField(blank=True, choices=[('일반', '일반'), ('긴급', '긴급')], default='일반', max_length=10)),
                ('생산목표수량', models.IntegerField()),
            ],
            options={
                'verbose_name': '생산의뢰등록',
                'verbose_name_plural': '생산의뢰등록',
            },
        ),
        migrations.CreateModel(
            name='OrderRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('수주코드', models.CharField(max_length=50)),
                ('영업구분', models.CharField(blank=True, choices=[('입찰', '입찰'), ('대리점', '대리점'), ('A/S', 'A/S'), ('내부계획', '내부계획')], default='입찰', max_length=10)),
                ('제품구분', models.CharField(blank=True, choices=[('단품', '단품'), ('랙', '랙')], default='단품', max_length=10)),
                ('사업장구분', models.CharField(blank=True, choices=[('삼형전자', '삼형전자'), ('엠에스텔레콤', '엠에스텔레콤')], default='삼형전자', max_length=10)),
                ('수주일자', models.DateField()),
                ('현장명', models.CharField(max_length=50)),
                ('납품요청일', models.DateField()),
                ('납품수량', models.IntegerField()),
                ('특이사항', models.TextField(blank=True)),
                ('고객사명', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='수주등록', to='StandardInformation.CustomerPartner')),
                ('단품모델', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='수주등록', to='StandardInformation.SingleProduct')),
                ('랙모델', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='수주등록', to='StandardInformation.RackProduct')),
            ],
            options={
                'verbose_name': '수주등록',
                'verbose_name_plural': '수주등록',
            },
        ),
        migrations.AddField(
            model_name='orderproduce',
            name='생산의뢰수주',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='생산요청', to='orders.OrderRegister'),
        ),
    ]
