# Generated by Django 2.1.15 on 2020-02-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderregister',
            name='납품요청일',
            field=models.DateField(blank=True, null=True),
        ),
    ]
