# Generated by Django 2.1.15 on 2020-02-16 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_auto_20200215_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderregister',
            name='작성자',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='수주등록', to=settings.AUTH_USER_MODEL),
        ),
    ]
