# Generated by Django 2.1.15 on 2020-02-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200216_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderregister',
            name='출하구분',
            field=models.CharField(blank=True, choices=[('출하완료', '출하완료'), ('출하미완료', '출하미완료')], default='출하미완료', max_length=10),
        ),
    ]
