# Generated by Django 2.1.15 on 2020-03-08 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderregister_랙생산의뢰'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderregister',
            name='랙생산의뢰',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='단품생산의뢰', to='orders.OrderRegister'),
        ),
    ]
