# Generated by Django 2.1.15 on 2020-03-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200308_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderregister',
            name='랙조립도면',
            field=models.FileField(blank=True, help_text='랙 수주의 경우 조립도면을 첨부해주세요.', null=True, upload_to='blueprint'),
        ),
    ]
