# Generated by Django 2.1.15 on 2020-03-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderregister_랙조립도면'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderregister',
            name='영업구분',
            field=models.CharField(blank=True, choices=[('입찰', '입찰'), ('대리점', '대리점'), ('A/S', 'A/S'), ('내부계획', '내부계획'), ('월별생산계획', '월별생산계획')], default='입찰', max_length=10),
        ),
    ]
