# Generated by Django 2.1.15 on 2020-08-21 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200331_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderregister',
            name='고객사명',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='수주등록', to='StandardInformation.Partner'),
        ),
    ]
